FROM node:14-alpine as build-deps

ARG BACKEND_URL
ENV REACT_APP_BACKEND_URL=$BACKEND_URL

WORKDIR /usr/src/app
COPY ./package.json ./package-lock.json ./
RUN npm ci
COPY ./ ./
RUN npm run build

FROM nginx:1.17
COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
