import { HttpCode, HttpStatus } from "@nestjs/common";

export const USER_CREATED_OK = 'USER CREATED SUCCESSFULLY';
export const USER_CREATED_KO = 'ERRORS OCCURRED WHILE CREATING THE USER !';
export const USER_VALIDATED_OK = 'USER VALIDATED SUCCESSFULLY';
export const USER_VALIDATED_KO = 'ERRORS OCCURRED WHILE VALIDATING THE USER !';

export const USER_PASSWORD_KO = 'PASSWORD EMPTY OR NOT SUFFICIENT !';
export const USER_PHONE_NBR_KO = 'PHONE NUMBER EMPTY OR IS NOT CORRECT !';
export const USER_EMAIL_KO = 'EMAIL EMPTY OR IS NOT CORRECT !';
export const USER_OTP_KO = 'OTP EMPTY OR IS NOT CORRECT !';
export const USER_LOGIN_DUPLICATE_KO =
  'DUPLICATE USER FOUND, UNAUTHORIZED LOGIN  !';
export const USER_LOGIN_NOTFOUND_KO = 'USER NOT FOUND, UNAUTHORIZED LOGIN  !';

export const USER_NOT_FOUND = 'REQUESTED USER NOT FOUND !';
export const USER_DUPLICATE = 'REQUESTED USER ALREADY EXISTS !';

export const USER_ALREADY_ACTIVATED = 'USER ALREADY ACTIVATED !';
export const USER_OTP_EXPIRED = 'OTP IS EXPIRED !';
export const USER_OTP_NOT_FOUND = 'USER OTP EMPTY OR IS NOT CORRECT !';
export const USER_ACTIVATED = 'USER ACTIVATED SUCCESSFULLY';
