import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1773225190627 implements MigrationInterface {
    name = 'Migrations1773225190627'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`user_roles\` (\`id\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`role\` varchar(20) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_5f9286e6c25594c6b88c108db7\` (\`userId\`, \`role\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`properties\` (\`id\` varchar(36) NOT NULL, \`hostId\` int NOT NULL, \`title\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`propertyType\` varchar(20) NOT NULL, \`status\` varchar(20) NOT NULL DEFAULT 'draft', \`pricePerNight\` decimal(12,2) NOT NULL, \`currency\` varchar(3) NOT NULL DEFAULT 'DZD', \`pricePerWeek\` decimal(12,2) NULL, \`pricePerMonth\` decimal(12,2) NULL, \`weeklyDiscount\` decimal(5,2) NULL, \`monthlyDiscount\` decimal(5,2) NULL, \`customDiscount\` decimal(5,2) NULL, \`customDiscountMinNights\` int NULL, \`cleaningFee\` decimal(12,2) NULL, \`serviceFeePercent\` decimal(5,2) NOT NULL DEFAULT '5.00', \`acceptedPaymentMethods\` json NULL, \`latitude\` decimal(10,7) NOT NULL, \`longitude\` decimal(10,7) NOT NULL, \`address\` varchar(500) NOT NULL, \`city\` varchar(100) NOT NULL, \`wilaya\` varchar(100) NOT NULL, \`country\` varchar(100) NOT NULL DEFAULT 'Algeria', \`zipCode\` varchar(10) NULL, \`maxGuests\` int NOT NULL, \`bedrooms\` int NOT NULL, \`bathrooms\` int NOT NULL, \`beds\` int NOT NULL DEFAULT '0', \`images\` json NOT NULL, \`amenities\` json NOT NULL, \`checkInTime\` varchar(5) NOT NULL DEFAULT '14:00', \`checkOutTime\` varchar(5) NOT NULL DEFAULT '11:00', \`houseRules\` json NULL, \`cancellationPolicy\` varchar(50) NOT NULL DEFAULT 'flexible', \`averageRating\` decimal(3,2) NOT NULL DEFAULT '0.00', \`reviewCount\` int NOT NULL DEFAULT '0', \`bookingCount\` int NOT NULL DEFAULT '0', \`isAvailable\` tinyint NOT NULL DEFAULT 1, \`trustStars\` int NOT NULL DEFAULT '0', \`isVerified\` tinyint NOT NULL DEFAULT 0, \`instantBooking\` tinyint NOT NULL DEFAULT 0, \`minNights\` int NOT NULL DEFAULT '1', \`maxNights\` int NOT NULL DEFAULT '365', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`property_groups\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`adminId\` int NOT NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`manager_assignments\` (\`id\` varchar(36) NOT NULL, \`managerId\` int NOT NULL, \`assignedByAdminId\` int NOT NULL, \`scope\` varchar(20) NOT NULL, \`propertyId\` varchar(255) NULL, \`propertyGroupId\` varchar(255) NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`manager_permissions\` (\`id\` varchar(36) NOT NULL, \`assignmentId\` varchar(255) NOT NULL, \`permission\` varchar(50) NOT NULL, \`isGranted\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_50d3d0212e12f49f2bba0faad5\` (\`assignmentId\`, \`permission\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`bookings\` (\`id\` varchar(36) NOT NULL, \`propertyId\` varchar(255) NOT NULL, \`guestId\` int NOT NULL, \`checkInDate\` date NOT NULL, \`checkOutDate\` date NOT NULL, \`numberOfGuests\` int NOT NULL, \`numberOfNights\` int NOT NULL, \`pricePerNight\` decimal(12,2) NOT NULL, \`cleaningFee\` decimal(12,2) NOT NULL DEFAULT '0.00', \`serviceFee\` decimal(12,2) NOT NULL DEFAULT '0.00', \`discountPercent\` decimal(5,2) NOT NULL DEFAULT '0.00', \`discountType\` varchar(50) NULL, \`effectiveRate\` decimal(12,2) NOT NULL, \`subtotal\` decimal(12,2) NOT NULL, \`totalPrice\` decimal(12,2) NOT NULL, \`currency\` varchar(3) NOT NULL DEFAULT 'DZD', \`status\` varchar(20) NOT NULL DEFAULT 'pending', \`paymentStatus\` varchar(20) NOT NULL DEFAULT 'pending', \`paymentMethod\` varchar(20) NULL, \`guestMessage\` text NULL, \`hostResponse\` text NULL, \`confirmedAt\` datetime NULL, \`cancelledAt\` datetime NULL, \`cancellationReason\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reviews\` (\`id\` varchar(36) NOT NULL, \`propertyId\` varchar(255) NOT NULL, \`guestId\` int NOT NULL, \`bookingId\` varchar(255) NOT NULL, \`overallRating\` int NOT NULL, \`cleanlinessRating\` int NULL, \`accuracyRating\` int NULL, \`communicationRating\` int NULL, \`locationRating\` int NULL, \`valueRating\` int NULL, \`checkInRating\` int NULL, \`comment\` text NOT NULL, \`hostReply\` text NULL, \`hostReplyAt\` datetime NULL, \`isPublic\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_c357057587a1c2afae453515bf\` (\`bookingId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reactions\` (\`id\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`type\` varchar(255) NOT NULL, \`targetType\` varchar(255) NOT NULL, \`targetId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_989f04b0d4b2c2513421b05aea\` (\`userId\`, \`targetType\`, \`targetId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`rankings\` (\`id\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`score\` int NOT NULL DEFAULT '0', \`previousRank\` int NULL, \`category\` varchar(255) NULL, \`metadata\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`verification_documents\` (\`id\` varchar(36) NOT NULL, \`propertyId\` varchar(255) NOT NULL, \`type\` varchar(30) NOT NULL, \`fileName\` varchar(255) NOT NULL, \`fileUrl\` varchar(500) NOT NULL, \`status\` varchar(20) NOT NULL DEFAULT 'pending', \`reviewNote\` text NULL, \`reviewedBy\` int NULL, \`reviewedAt\` datetime NULL, \`aiAnalyzed\` tinyint NULL, \`aiValidationResult\` tinyint NULL, \`aiConfidence\` float NULL, \`aiReason\` text NULL, \`aiDetectedIssues\` json NULL, \`aiAnalyzedAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`property_group_memberships\` (\`id\` varchar(36) NOT NULL, \`propertyId\` varchar(255) NOT NULL, \`groupId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_b977e6070809644106601ae48c\` (\`propertyId\`, \`groupId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`property_images\` (\`id\` varchar(36) NOT NULL, \`propertyId\` varchar(255) NOT NULL, \`url\` varchar(1000) NOT NULL, \`caption\` varchar(255) NULL, \`sortOrder\` int NOT NULL DEFAULT '0', \`isCover\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`property_availability\` (\`id\` varchar(36) NOT NULL, \`propertyId\` varchar(255) NOT NULL, \`date\` date NOT NULL, \`isBlocked\` tinyint NOT NULL DEFAULT 0, \`customPrice\` decimal(12,2) NULL, UNIQUE INDEX \`IDX_1be3614f0c4a528ceeb5b21b54\` (\`propertyId\`, \`date\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`profiles\` (\`id\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`displayName\` varchar(255) NULL, \`avatarUrl\` varchar(1000) NULL, \`bio\` text NULL, \`phoneNumber\` varchar(20) NULL, \`phoneVerified\` tinyint NOT NULL DEFAULT 0, \`city\` varchar(100) NULL, \`wilaya\` varchar(100) NULL, \`country\` varchar(100) NOT NULL DEFAULT 'Algeria', \`languages\` json NULL, \`isHost\` tinyint NOT NULL DEFAULT 0, \`isSuperhost\` tinyint NOT NULL DEFAULT 0, \`identityVerified\` tinyint NOT NULL DEFAULT 0, \`hostSince\` datetime NULL, \`hostRating\` decimal(3,2) NOT NULL DEFAULT '0.00', \`totalReviews\` int NOT NULL DEFAULT '0', \`preferredLanguage\` varchar(10) NOT NULL DEFAULT 'fr', \`preferredCurrency\` varchar(3) NOT NULL DEFAULT 'DZD', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_315ecd98bd1a42dcf2ec4e2e98\` (\`userId\`), UNIQUE INDEX \`REL_315ecd98bd1a42dcf2ec4e2e98\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`type\` varchar(30) NOT NULL DEFAULT 'general', \`title\` varchar(255) NOT NULL, \`message\` text NOT NULL, \`channel\` varchar(10) NOT NULL DEFAULT 'in_app', \`isRead\` tinyint NOT NULL DEFAULT 0, \`actionUrl\` varchar(500) NULL, \`metadata\` json NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`favorites\` (\`id\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`propertyId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_f9c880e929c6fa3bdb17c3f6d1\` (\`userId\`, \`propertyId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`comments\` (\`id\` varchar(36) NOT NULL, \`content\` text NOT NULL, \`userId\` int NOT NULL, \`parentId\` varchar(255) NULL, \`targetType\` varchar(255) NULL, \`targetId\` varchar(255) NULL, \`media\` text NULL, \`mentions\` text NULL, \`isEdited\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_472b25323af01488f1f66a06b67\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`properties\` ADD CONSTRAINT \`FK_97ae9ee8402b8d8d167fa7352ce\` FOREIGN KEY (\`hostId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`property_groups\` ADD CONSTRAINT \`FK_b6d936acb749bb33c957bb64a9e\` FOREIGN KEY (\`adminId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`manager_assignments\` ADD CONSTRAINT \`FK_89bf0c2c003b0888088b2fbeaa7\` FOREIGN KEY (\`managerId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`manager_assignments\` ADD CONSTRAINT \`FK_a481b85a26542b303daf1299603\` FOREIGN KEY (\`assignedByAdminId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`manager_assignments\` ADD CONSTRAINT \`FK_e9ceb07f2116e7d89fdc718a586\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`manager_assignments\` ADD CONSTRAINT \`FK_5d989ea14604459b64788db8c63\` FOREIGN KEY (\`propertyGroupId\`) REFERENCES \`property_groups\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`manager_permissions\` ADD CONSTRAINT \`FK_47e0d2c52f1f2f2759d98be78fd\` FOREIGN KEY (\`assignmentId\`) REFERENCES \`manager_assignments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD CONSTRAINT \`FK_cf064476d403971270369232d80\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD CONSTRAINT \`FK_28306518087b40a95df05a43624\` FOREIGN KEY (\`guestId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_2c75ccf95bf502363885d076e76\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_443cc60218090a17d96ea64b058\` FOREIGN KEY (\`guestId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_c357057587a1c2afae453515bf6\` FOREIGN KEY (\`bookingId\`) REFERENCES \`bookings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`verification_documents\` ADD CONSTRAINT \`FK_83c2693bf96ad158cfb00db3a6d\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`property_group_memberships\` ADD CONSTRAINT \`FK_1e49e229423390107900cad0054\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`property_group_memberships\` ADD CONSTRAINT \`FK_abd19027800f0198931c5295407\` FOREIGN KEY (\`groupId\`) REFERENCES \`property_groups\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`property_images\` ADD CONSTRAINT \`FK_7a07b6b7f9418bf1d5160106694\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`property_availability\` ADD CONSTRAINT \`FK_72a85a891e574c9a08f6f62edc8\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`profiles\` ADD CONSTRAINT \`FK_315ecd98bd1a42dcf2ec4e2e985\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_692a909ee0fa9383e7859f9b406\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`favorites\` ADD CONSTRAINT \`FK_e747534006c6e3c2f09939da60f\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`favorites\` ADD CONSTRAINT \`FK_39fd1b53d2b44d5bc1d766f9a2a\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_7e8d7c49f218ebb14314fdb3749\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_7e8d7c49f218ebb14314fdb3749\``);
        await queryRunner.query(`ALTER TABLE \`favorites\` DROP FOREIGN KEY \`FK_39fd1b53d2b44d5bc1d766f9a2a\``);
        await queryRunner.query(`ALTER TABLE \`favorites\` DROP FOREIGN KEY \`FK_e747534006c6e3c2f09939da60f\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_692a909ee0fa9383e7859f9b406\``);
        await queryRunner.query(`ALTER TABLE \`profiles\` DROP FOREIGN KEY \`FK_315ecd98bd1a42dcf2ec4e2e985\``);
        await queryRunner.query(`ALTER TABLE \`property_availability\` DROP FOREIGN KEY \`FK_72a85a891e574c9a08f6f62edc8\``);
        await queryRunner.query(`ALTER TABLE \`property_images\` DROP FOREIGN KEY \`FK_7a07b6b7f9418bf1d5160106694\``);
        await queryRunner.query(`ALTER TABLE \`property_group_memberships\` DROP FOREIGN KEY \`FK_abd19027800f0198931c5295407\``);
        await queryRunner.query(`ALTER TABLE \`property_group_memberships\` DROP FOREIGN KEY \`FK_1e49e229423390107900cad0054\``);
        await queryRunner.query(`ALTER TABLE \`verification_documents\` DROP FOREIGN KEY \`FK_83c2693bf96ad158cfb00db3a6d\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_c357057587a1c2afae453515bf6\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_443cc60218090a17d96ea64b058\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_2c75ccf95bf502363885d076e76\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP FOREIGN KEY \`FK_28306518087b40a95df05a43624\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP FOREIGN KEY \`FK_cf064476d403971270369232d80\``);
        await queryRunner.query(`ALTER TABLE \`manager_permissions\` DROP FOREIGN KEY \`FK_47e0d2c52f1f2f2759d98be78fd\``);
        await queryRunner.query(`ALTER TABLE \`manager_assignments\` DROP FOREIGN KEY \`FK_5d989ea14604459b64788db8c63\``);
        await queryRunner.query(`ALTER TABLE \`manager_assignments\` DROP FOREIGN KEY \`FK_e9ceb07f2116e7d89fdc718a586\``);
        await queryRunner.query(`ALTER TABLE \`manager_assignments\` DROP FOREIGN KEY \`FK_a481b85a26542b303daf1299603\``);
        await queryRunner.query(`ALTER TABLE \`manager_assignments\` DROP FOREIGN KEY \`FK_89bf0c2c003b0888088b2fbeaa7\``);
        await queryRunner.query(`ALTER TABLE \`property_groups\` DROP FOREIGN KEY \`FK_b6d936acb749bb33c957bb64a9e\``);
        await queryRunner.query(`ALTER TABLE \`properties\` DROP FOREIGN KEY \`FK_97ae9ee8402b8d8d167fa7352ce\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_472b25323af01488f1f66a06b67\``);
        await queryRunner.query(`DROP TABLE \`comments\``);
        await queryRunner.query(`DROP INDEX \`IDX_f9c880e929c6fa3bdb17c3f6d1\` ON \`favorites\``);
        await queryRunner.query(`DROP TABLE \`favorites\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP INDEX \`REL_315ecd98bd1a42dcf2ec4e2e98\` ON \`profiles\``);
        await queryRunner.query(`DROP INDEX \`IDX_315ecd98bd1a42dcf2ec4e2e98\` ON \`profiles\``);
        await queryRunner.query(`DROP TABLE \`profiles\``);
        await queryRunner.query(`DROP INDEX \`IDX_1be3614f0c4a528ceeb5b21b54\` ON \`property_availability\``);
        await queryRunner.query(`DROP TABLE \`property_availability\``);
        await queryRunner.query(`DROP TABLE \`property_images\``);
        await queryRunner.query(`DROP INDEX \`IDX_b977e6070809644106601ae48c\` ON \`property_group_memberships\``);
        await queryRunner.query(`DROP TABLE \`property_group_memberships\``);
        await queryRunner.query(`DROP TABLE \`verification_documents\``);
        await queryRunner.query(`DROP TABLE \`rankings\``);
        await queryRunner.query(`DROP INDEX \`IDX_989f04b0d4b2c2513421b05aea\` ON \`reactions\``);
        await queryRunner.query(`DROP TABLE \`reactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_c357057587a1c2afae453515bf\` ON \`reviews\``);
        await queryRunner.query(`DROP TABLE \`reviews\``);
        await queryRunner.query(`DROP TABLE \`bookings\``);
        await queryRunner.query(`DROP INDEX \`IDX_50d3d0212e12f49f2bba0faad5\` ON \`manager_permissions\``);
        await queryRunner.query(`DROP TABLE \`manager_permissions\``);
        await queryRunner.query(`DROP TABLE \`manager_assignments\``);
        await queryRunner.query(`DROP TABLE \`property_groups\``);
        await queryRunner.query(`DROP TABLE \`properties\``);
        await queryRunner.query(`DROP INDEX \`IDX_5f9286e6c25594c6b88c108db7\` ON \`user_roles\``);
        await queryRunner.query(`DROP TABLE \`user_roles\``);
    }

}
