import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1774866293534 implements MigrationInterface {
    name = 'Migrations1774866293534'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`users_address\` (\`id\` int NOT NULL AUTO_INCREMENT, \`city\` varchar(255) NULL, \`zipcode\` varchar(255) NULL, \`address\` varchar(255) NULL, \`country\` varchar(255) NULL, \`otherPhoneNbr\` varchar(255) NULL, \`otherEmail\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`email\` varchar(255) NULL, \`phoneNbr\` varchar(255) NOT NULL, \`cardId\` varchar(255) NOT NULL, \`passportId\` varchar(255) NULL, \`roles\` varchar(255) NOT NULL, \`lastName\` varchar(255) NOT NULL, \`firstName\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`token\` varchar(255) NOT NULL, \`tokenExpirationDate\` datetime NULL, \`otp\` varchar(255) NULL, \`otpExpirationDate\` datetime NULL, \`title\` varchar(255) NULL, \`city\` varchar(255) NULL, \`zipcode\` varchar(255) NULL, \`address\` varchar(255) NULL, \`country\` varchar(255) NULL, \`secondPhoneNbr\` varchar(255) NULL, \`resetToken\` varchar(255) NULL, \`passwordCreatedAt\` datetime NULL, \`passwordUpdatedAt\` datetime NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), UNIQUE INDEX \`IDX_75b3a5d8f99f184a376a414542\` (\`phoneNbr\`), UNIQUE INDEX \`IDX_501578f69c24fba9ec42553591\` (\`cardId\`), UNIQUE INDEX \`IDX_53a51a9023bb1e952b1f840312\` (\`passportId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_roles\` (\`id\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`role\` varchar(20) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_5f9286e6c25594c6b88c108db7\` (\`userId\`, \`role\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`properties\` (\`id\` varchar(36) NOT NULL, \`hostId\` int NOT NULL, \`title\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`propertyType\` varchar(20) NOT NULL, \`status\` varchar(20) NOT NULL DEFAULT 'draft', \`pricePerNight\` decimal(12,2) NOT NULL, \`currency\` varchar(3) NOT NULL DEFAULT 'DZD', \`pricePerWeek\` decimal(12,2) NULL, \`pricePerMonth\` decimal(12,2) NULL, \`weeklyDiscount\` decimal(5,2) NULL, \`monthlyDiscount\` decimal(5,2) NULL, \`customDiscount\` decimal(5,2) NULL, \`customDiscountMinNights\` int NULL, \`cleaningFee\` decimal(12,2) NULL, \`serviceFeePercent\` decimal(5,2) NOT NULL DEFAULT '5.00', \`acceptedPaymentMethods\` json NULL, \`latitude\` decimal(10,7) NOT NULL, \`longitude\` decimal(10,7) NOT NULL, \`address\` varchar(500) NOT NULL, \`city\` varchar(100) NOT NULL, \`wilaya\` varchar(100) NOT NULL, \`country\` varchar(100) NOT NULL DEFAULT 'Algeria', \`zipCode\` varchar(10) NULL, \`maxGuests\` int NOT NULL, \`bedrooms\` int NOT NULL, \`bathrooms\` int NOT NULL, \`beds\` int NOT NULL DEFAULT '0', \`images\` json NOT NULL, \`amenities\` json NOT NULL, \`checkInTime\` varchar(5) NOT NULL DEFAULT '14:00', \`checkOutTime\` varchar(5) NOT NULL DEFAULT '11:00', \`houseRules\` json NULL, \`cancellationPolicy\` varchar(50) NOT NULL DEFAULT 'flexible', \`averageRating\` decimal(3,2) NOT NULL DEFAULT '0.00', \`reviewCount\` int NOT NULL DEFAULT '0', \`bookingCount\` int NOT NULL DEFAULT '0', \`isAvailable\` tinyint NOT NULL DEFAULT 1, \`trustStars\` int NOT NULL DEFAULT '0', \`isVerified\` tinyint NOT NULL DEFAULT 0, \`instantBooking\` tinyint NOT NULL DEFAULT 0, \`allowPets\` tinyint NOT NULL DEFAULT 0, \`minNights\` int NOT NULL DEFAULT '1', \`maxNights\` int NOT NULL DEFAULT '365', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_properties_hostId\` (\`hostId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`property_groups\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`adminId\` int NOT NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`manager_assignments\` (\`id\` varchar(36) NOT NULL, \`managerId\` int NOT NULL, \`assignedByAdminId\` int NOT NULL, \`scope\` varchar(20) NOT NULL, \`propertyId\` varchar(255) NULL, \`propertyGroupId\` varchar(255) NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`manager_permissions\` (\`id\` varchar(36) NOT NULL, \`assignmentId\` varchar(255) NOT NULL, \`permission\` varchar(50) NOT NULL, \`isGranted\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_50d3d0212e12f49f2bba0faad5\` (\`assignmentId\`, \`permission\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`invitations\` (\`id\` varchar(36) NOT NULL, \`method\` varchar(10) NOT NULL, \`email\` varchar(255) NULL, \`phone\` varchar(255) NULL, \`role\` varchar(20) NOT NULL, \`status\` varchar(20) NOT NULL DEFAULT 'pending', \`invitedBy\` int NOT NULL, \`token\` varchar(255) NULL, \`message\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`expiresAt\` timestamp NULL, \`acceptedAt\` timestamp NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`support_threads\` (\`id\` varchar(36) NOT NULL, \`subject\` varchar(255) NOT NULL, \`category\` varchar(50) NOT NULL DEFAULT 'general', \`status\` varchar(20) NOT NULL DEFAULT 'open', \`initiatorId\` int NOT NULL, \`assignedAdminId\` int NULL, \`propertyId\` varchar(255) NULL, \`bookingId\` varchar(255) NULL, \`reviewId\` varchar(255) NULL, \`unreadCountAdmin\` int NOT NULL DEFAULT '0', \`unreadCountUser\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_support_thread_initiator\` (\`initiatorId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`support_messages\` (\`id\` varchar(36) NOT NULL, \`threadId\` varchar(255) NOT NULL, \`senderId\` int NOT NULL, \`senderRole\` varchar(20) NOT NULL, \`content\` text NOT NULL, \`isSystemMessage\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_support_message_thread\` (\`threadId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_preferences\` (\`id\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`language\` varchar(10) NOT NULL DEFAULT 'fr', \`theme\` varchar(20) NOT NULL DEFAULT 'system', \`dateFormat\` varchar(20) NOT NULL DEFAULT 'DD/MM/YYYY', \`timezone\` varchar(50) NOT NULL DEFAULT 'Africa/Algiers', \`currency\` varchar(3) NOT NULL DEFAULT 'DZD', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_b6202d1cacc63a0b9c8dac2abd\` (\`userId\`), UNIQUE INDEX \`REL_b6202d1cacc63a0b9c8dac2abd\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notification_settings\` (\`id\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`emailNotifications\` tinyint NOT NULL DEFAULT 1, \`pushNotifications\` tinyint NOT NULL DEFAULT 1, \`marketingEmails\` tinyint NOT NULL DEFAULT 0, \`securityAlerts\` tinyint NOT NULL DEFAULT 1, \`weeklyDigest\` tinyint NOT NULL DEFAULT 0, \`commentReplies\` tinyint NOT NULL DEFAULT 1, \`commentRepliesPush\` tinyint NOT NULL DEFAULT 1, \`rankingUpdates\` tinyint NOT NULL DEFAULT 1, \`rankingUpdatesPush\` tinyint NOT NULL DEFAULT 0, \`newFollowers\` tinyint NOT NULL DEFAULT 1, \`newFollowersPush\` tinyint NOT NULL DEFAULT 1, \`systemAnnouncements\` tinyint NOT NULL DEFAULT 1, \`systemAnnouncementsPush\` tinyint NOT NULL DEFAULT 1, \`quietHoursEnabled\` tinyint NOT NULL DEFAULT 0, \`quietHoursStart\` varchar(5) NOT NULL DEFAULT '22:00', \`quietHoursEnd\` varchar(5) NOT NULL DEFAULT '07:00', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_5a8ffc3b89343043c9440d631e\` (\`userId\`), UNIQUE INDEX \`REL_5a8ffc3b89343043c9440d631e\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tourism_services\` (\`id\` varchar(36) NOT NULL, \`providerId\` int NOT NULL, \`title\` json NOT NULL, \`description\` json NOT NULL, \`category\` varchar(30) NOT NULL, \`status\` varchar(20) NOT NULL DEFAULT 'draft', \`price\` decimal(12,2) NOT NULL, \`currency\` varchar(3) NOT NULL DEFAULT 'DZD', \`pricingType\` varchar(20) NOT NULL DEFAULT 'per_person', \`priceChild\` decimal(12,2) NULL, \`groupDiscount\` decimal(5,2) NULL, \`duration\` int NULL, \`durationUnit\` varchar(10) NOT NULL DEFAULT 'hours', \`minParticipants\` int NOT NULL DEFAULT '1', \`maxParticipants\` int NOT NULL DEFAULT '20', \`latitude\` decimal(10,7) NULL, \`longitude\` decimal(10,7) NULL, \`address\` varchar(500) NULL, \`city\` varchar(100) NOT NULL, \`wilaya\` varchar(100) NOT NULL, \`country\` varchar(100) NOT NULL DEFAULT 'Algeria', \`images\` json NULL, \`includes\` json NULL, \`requirements\` json NULL, \`schedule\` json NULL, \`languages\` json NULL, \`tags\` json NULL, \`averageRating\` decimal(3,2) NOT NULL DEFAULT '0.00', \`reviewCount\` int NOT NULL DEFAULT '0', \`bookingCount\` int NOT NULL DEFAULT '0', \`isAvailable\` tinyint NOT NULL DEFAULT 1, \`isVerified\` tinyint NOT NULL DEFAULT 0, \`instantBooking\` tinyint NOT NULL DEFAULT 0, \`minAge\` int NOT NULL DEFAULT '0', \`cancellationPolicy\` varchar(50) NOT NULL DEFAULT 'flexible', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_services_providerId\` (\`providerId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`bookings\` (\`id\` varchar(36) NOT NULL, \`propertyId\` varchar(255) NOT NULL, \`guestId\` int NOT NULL, \`checkInDate\` date NOT NULL, \`checkOutDate\` date NOT NULL, \`numberOfGuests\` int NOT NULL, \`numberOfNights\` int NOT NULL, \`pricePerNight\` decimal(12,2) NOT NULL, \`cleaningFee\` decimal(12,2) NOT NULL DEFAULT '0.00', \`serviceFee\` decimal(12,2) NOT NULL DEFAULT '0.00', \`discountPercent\` decimal(5,2) NOT NULL DEFAULT '0.00', \`discountType\` varchar(50) NULL, \`effectiveRate\` decimal(12,2) NOT NULL, \`subtotal\` decimal(12,2) NOT NULL, \`totalPrice\` decimal(12,2) NOT NULL, \`currency\` varchar(3) NOT NULL DEFAULT 'DZD', \`status\` varchar(20) NOT NULL DEFAULT 'pending', \`paymentStatus\` varchar(20) NOT NULL DEFAULT 'pending', \`paymentMethod\` varchar(20) NULL, \`guestMessage\` text NULL, \`hostResponse\` text NULL, \`confirmedAt\` datetime NULL, \`cancelledAt\` datetime NULL, \`cancellationReason\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_bookings_propertyId\` (\`propertyId\`), INDEX \`IDX_bookings_guestId\` (\`guestId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reviews\` (\`id\` varchar(36) NOT NULL, \`propertyId\` varchar(255) NOT NULL, \`guestId\` int NOT NULL, \`bookingId\` varchar(255) NOT NULL, \`overallRating\` int NOT NULL, \`hostRating\` int NULL, \`cleanlinessRating\` int NULL, \`accuracyRating\` int NULL, \`communicationRating\` int NULL, \`locationRating\` int NULL, \`valueRating\` int NULL, \`checkInRating\` int NULL, \`comment\` text NOT NULL, \`hostReply\` text NULL, \`hostReplyAt\` datetime NULL, \`isPublic\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_reviews_propertyId\` (\`propertyId\`), INDEX \`IDX_reviews_guestId\` (\`guestId\`), UNIQUE INDEX \`IDX_c357057587a1c2afae453515bf\` (\`bookingId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reactions\` (\`id\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`type\` varchar(255) NOT NULL, \`targetType\` varchar(255) NOT NULL, \`targetId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_reactions_userId\` (\`userId\`), UNIQUE INDEX \`IDX_989f04b0d4b2c2513421b05aea\` (\`userId\`, \`targetType\`, \`targetId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`rankings\` (\`id\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`score\` int NOT NULL DEFAULT '0', \`previousRank\` int NULL, \`category\` varchar(255) NULL, \`metadata\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_rankings_userId\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`verification_documents\` (\`id\` varchar(36) NOT NULL, \`propertyId\` varchar(255) NOT NULL, \`type\` varchar(30) NOT NULL, \`fileName\` varchar(255) NOT NULL, \`fileUrl\` varchar(500) NOT NULL, \`status\` varchar(20) NOT NULL DEFAULT 'pending', \`reviewNote\` text NULL, \`reviewedBy\` int NULL, \`reviewedAt\` datetime NULL, \`aiAnalyzed\` tinyint NULL, \`aiValidationResult\` tinyint NULL, \`aiConfidence\` float NULL, \`aiReason\` text NULL, \`aiDetectedIssues\` json NULL, \`aiAnalyzedAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_verification_docs_propertyId\` (\`propertyId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`saved_search_alerts\` (\`id\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`name\` varchar(255) NOT NULL, \`criteria\` json NOT NULL, \`frequency\` varchar(20) NOT NULL DEFAULT 'daily', \`channels\` json NOT NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`lastTriggeredAt\` timestamp NULL, \`matchCount\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`property_promos\` (\`id\` varchar(36) NOT NULL, \`propertyId\` varchar(255) NOT NULL, \`startDate\` date NOT NULL, \`endDate\` date NOT NULL, \`discountPercent\` decimal(5,2) NOT NULL, \`fixedPrice\` decimal(12,2) NULL, \`label\` varchar(255) NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`property_images\` (\`id\` varchar(36) NOT NULL, \`propertyId\` varchar(255) NOT NULL, \`url\` varchar(1000) NOT NULL, \`caption\` varchar(255) NULL, \`sortOrder\` int NOT NULL DEFAULT '0', \`isCover\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_property_images_propertyId\` (\`propertyId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`property_group_memberships\` (\`id\` varchar(36) NOT NULL, \`propertyId\` varchar(255) NOT NULL, \`groupId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_b977e6070809644106601ae48c\` (\`propertyId\`, \`groupId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`property_availability\` (\`id\` varchar(36) NOT NULL, \`propertyId\` varchar(255) NOT NULL, \`date\` date NOT NULL, \`isBlocked\` tinyint NOT NULL DEFAULT 0, \`customPrice\` decimal(12,2) NULL, UNIQUE INDEX \`IDX_1be3614f0c4a528ceeb5b21b54\` (\`propertyId\`, \`date\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`promo_alerts\` (\`id\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`propertyId\` varchar(255) NOT NULL, \`notifyEmail\` tinyint NOT NULL DEFAULT 1, \`notifyPhone\` tinyint NOT NULL DEFAULT 0, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_6317dffa57c5917cb78fb8c4d1\` (\`userId\`, \`propertyId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`profiles\` (\`id\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`displayName\` varchar(255) NULL, \`avatarUrl\` varchar(1000) NULL, \`bio\` text NULL, \`phoneNumber\` varchar(20) NULL, \`phoneVerified\` tinyint NOT NULL DEFAULT 0, \`city\` varchar(100) NULL, \`wilaya\` varchar(100) NULL, \`country\` varchar(100) NOT NULL DEFAULT 'Algeria', \`languages\` json NULL, \`isHost\` tinyint NOT NULL DEFAULT 0, \`isSuperhost\` tinyint NOT NULL DEFAULT 0, \`identityVerified\` tinyint NOT NULL DEFAULT 0, \`hostSince\` datetime NULL, \`hostRating\` decimal(3,2) NOT NULL DEFAULT '0.00', \`totalReviews\` int NOT NULL DEFAULT '0', \`preferredLanguage\` varchar(10) NOT NULL DEFAULT 'fr', \`preferredCurrency\` varchar(3) NOT NULL DEFAULT 'DZD', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_315ecd98bd1a42dcf2ec4e2e98\` (\`userId\`), UNIQUE INDEX \`REL_315ecd98bd1a42dcf2ec4e2e98\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`transfer_accounts\` (\`id\` varchar(36) NOT NULL, \`bankName\` varchar(100) NOT NULL, \`accountType\` varchar(20) NOT NULL, \`accountNumber\` varchar(100) NOT NULL, \`accountKey\` varchar(20) NULL, \`holderName\` varchar(255) NOT NULL, \`agencyName\` varchar(255) NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`sortOrder\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payment_receipts\` (\`id\` varchar(36) NOT NULL, \`bookingId\` varchar(255) NOT NULL, \`uploadedByUserId\` int NOT NULL, \`transferAccountId\` varchar(255) NULL, \`receiptUrl\` varchar(1000) NOT NULL, \`originalFileName\` varchar(255) NULL, \`amount\` decimal(12,2) NOT NULL, \`currency\` varchar(3) NOT NULL DEFAULT 'DZD', \`status\` varchar(20) NOT NULL DEFAULT 'pending', \`reviewedByUserId\` int NULL, \`reviewedAt\` datetime NULL, \`reviewNote\` text NULL, \`guestNote\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`type\` varchar(30) NOT NULL DEFAULT 'general', \`title\` varchar(255) NOT NULL, \`message\` text NOT NULL, \`channel\` varchar(10) NOT NULL DEFAULT 'in_app', \`isRead\` tinyint NOT NULL DEFAULT 0, \`actionUrl\` varchar(500) NULL, \`metadata\` json NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_notifications_userId\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`
        CREATE TABLE \`email_tracked_links\` (
            \`id\` varchar(36) NOT NULL,
            \`trackingId\` varchar(64) NOT NULL,
            \`messageId\` varchar(255) NOT NULL,
            \`originalUrl\` varchar(2000) NOT NULL,
            \`linkTag\` varchar(255) NULL,
            \`recipientEmail\` varchar(255) NOT NULL,
            \`clickCount\` int NOT NULL DEFAULT '0',
            \`humanClickCount\` int NOT NULL DEFAULT '0',
            \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
            INDEX \`IDX_a1434de92f26fb6d950dcb0345\` (\`messageId\`),
            UNIQUE INDEX \`IDX_20382c8b78ced4c0fe9fed80ed\` (\`trackingId\`),
            PRIMARY KEY (\`id\`)
        ) ENGINE=InnoDB
        `);
        await queryRunner.query(`CREATE TABLE \`email_events\` (\`id\` varchar(36) NOT NULL, \`messageId\` varchar(255) NOT NULL, \`eventType\` varchar(30) NOT NULL, \`recipientEmail\` varchar(255) NOT NULL, \`subject\` varchar(255) NULL, \`templateName\` varchar(100) NULL, \`clickedUrl\` varchar(500) NULL, \`linkTag\` varchar(255) NULL, \`userAgent\` varchar(500) NULL, \`ipAddress\` varchar(45) NULL, \`isBot\` tinyint NOT NULL DEFAULT 0, \`botReason\` varchar(50) NULL, \`responseTimeMs\` int NULL, \`isHoneypot\` tinyint NOT NULL DEFAULT 0, \`jsVerified\` tinyint NOT NULL DEFAULT 0, \`metadata\` json NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`idx_email_created_at\` (\`createdAt\`), INDEX \`idx_email_event_type\` (\`eventType\`), INDEX \`idx_email_recipient_email\` (\`recipientEmail\`), INDEX \`idx_email_message_id\` (\`messageId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`favorites\` (\`id\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`propertyId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_favorites_userId\` (\`userId\`), INDEX \`IDX_favorites_propertyId\` (\`propertyId\`), UNIQUE INDEX \`IDX_f9c880e929c6fa3bdb17c3f6d1\` (\`userId\`, \`propertyId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`comments\` (\`id\` varchar(36) NOT NULL, \`content\` text NOT NULL, \`userId\` int NOT NULL, \`parentId\` varchar(255) NULL, \`targetType\` varchar(255) NULL, \`targetId\` varchar(255) NULL, \`media\` text NULL, \`mentions\` text NULL, \`isEdited\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_comments_userId\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_472b25323af01488f1f66a06b67\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`properties\` ADD CONSTRAINT \`FK_97ae9ee8402b8d8d167fa7352ce\` FOREIGN KEY (\`hostId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`property_groups\` ADD CONSTRAINT \`FK_b6d936acb749bb33c957bb64a9e\` FOREIGN KEY (\`adminId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`manager_assignments\` ADD CONSTRAINT \`FK_89bf0c2c003b0888088b2fbeaa7\` FOREIGN KEY (\`managerId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`manager_assignments\` ADD CONSTRAINT \`FK_a481b85a26542b303daf1299603\` FOREIGN KEY (\`assignedByAdminId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`manager_assignments\` ADD CONSTRAINT \`FK_e9ceb07f2116e7d89fdc718a586\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`manager_assignments\` ADD CONSTRAINT \`FK_5d989ea14604459b64788db8c63\` FOREIGN KEY (\`propertyGroupId\`) REFERENCES \`property_groups\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`manager_permissions\` ADD CONSTRAINT \`FK_47e0d2c52f1f2f2759d98be78fd\` FOREIGN KEY (\`assignmentId\`) REFERENCES \`manager_assignments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invitations\` ADD CONSTRAINT \`FK_b6c9f56adddc26272a8d8643f59\` FOREIGN KEY (\`invitedBy\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`support_threads\` ADD CONSTRAINT \`FK_8475449853d7fae8e59d66f9de7\` FOREIGN KEY (\`initiatorId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`support_threads\` ADD CONSTRAINT \`FK_4b5a435c5e0e30bccf46b83e3ba\` FOREIGN KEY (\`assignedAdminId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`support_messages\` ADD CONSTRAINT \`FK_af47c9fa96ed606ccf48e195521\` FOREIGN KEY (\`threadId\`) REFERENCES \`support_threads\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`support_messages\` ADD CONSTRAINT \`FK_a6d023327205aee297257d4f0fe\` FOREIGN KEY (\`senderId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_preferences\` ADD CONSTRAINT \`FK_b6202d1cacc63a0b9c8dac2abd4\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notification_settings\` ADD CONSTRAINT \`FK_5a8ffc3b89343043c9440d631e2\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tourism_services\` ADD CONSTRAINT \`FK_233b8e5e7662241350d529a48fa\` FOREIGN KEY (\`providerId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD CONSTRAINT \`FK_cf064476d403971270369232d80\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD CONSTRAINT \`FK_28306518087b40a95df05a43624\` FOREIGN KEY (\`guestId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_2c75ccf95bf502363885d076e76\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_443cc60218090a17d96ea64b058\` FOREIGN KEY (\`guestId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_c357057587a1c2afae453515bf6\` FOREIGN KEY (\`bookingId\`) REFERENCES \`bookings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`verification_documents\` ADD CONSTRAINT \`FK_83c2693bf96ad158cfb00db3a6d\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`saved_search_alerts\` ADD CONSTRAINT \`FK_83eb2719b230c0aca5d2020e589\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`property_promos\` ADD CONSTRAINT \`FK_870506fd9695699a078dfda11e7\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`property_images\` ADD CONSTRAINT \`FK_7a07b6b7f9418bf1d5160106694\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`property_group_memberships\` ADD CONSTRAINT \`FK_1e49e229423390107900cad0054\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`property_group_memberships\` ADD CONSTRAINT \`FK_abd19027800f0198931c5295407\` FOREIGN KEY (\`groupId\`) REFERENCES \`property_groups\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`property_availability\` ADD CONSTRAINT \`FK_72a85a891e574c9a08f6f62edc8\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo_alerts\` ADD CONSTRAINT \`FK_aab91d6f90e1b7c80cf2552780f\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promo_alerts\` ADD CONSTRAINT \`FK_786941dea2952d17e21626355d7\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`profiles\` ADD CONSTRAINT \`FK_315ecd98bd1a42dcf2ec4e2e985\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_receipts\` ADD CONSTRAINT \`FK_15f4d38dd33a2cfdbe5b4f0341a\` FOREIGN KEY (\`bookingId\`) REFERENCES \`bookings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_receipts\` ADD CONSTRAINT \`FK_51e32bf1cb2facff0caa451cb59\` FOREIGN KEY (\`uploadedByUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_receipts\` ADD CONSTRAINT \`FK_c0faea96a1f7235f8cd2a6e930f\` FOREIGN KEY (\`transferAccountId\`) REFERENCES \`transfer_accounts\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_receipts\` ADD CONSTRAINT \`FK_5f3e2d6b91e9b3fb5d250d4183a\` FOREIGN KEY (\`reviewedByUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_692a909ee0fa9383e7859f9b406\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`favorites\` ADD CONSTRAINT \`FK_e747534006c6e3c2f09939da60f\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`favorites\` ADD CONSTRAINT \`FK_39fd1b53d2b44d5bc1d766f9a2a\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_7e8d7c49f218ebb14314fdb3749\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_7e8d7c49f218ebb14314fdb3749\``);
        await queryRunner.query(`ALTER TABLE \`favorites\` DROP FOREIGN KEY \`FK_39fd1b53d2b44d5bc1d766f9a2a\``);
        await queryRunner.query(`ALTER TABLE \`favorites\` DROP FOREIGN KEY \`FK_e747534006c6e3c2f09939da60f\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_692a909ee0fa9383e7859f9b406\``);
        await queryRunner.query(`ALTER TABLE \`payment_receipts\` DROP FOREIGN KEY \`FK_5f3e2d6b91e9b3fb5d250d4183a\``);
        await queryRunner.query(`ALTER TABLE \`payment_receipts\` DROP FOREIGN KEY \`FK_c0faea96a1f7235f8cd2a6e930f\``);
        await queryRunner.query(`ALTER TABLE \`payment_receipts\` DROP FOREIGN KEY \`FK_51e32bf1cb2facff0caa451cb59\``);
        await queryRunner.query(`ALTER TABLE \`payment_receipts\` DROP FOREIGN KEY \`FK_15f4d38dd33a2cfdbe5b4f0341a\``);
        await queryRunner.query(`ALTER TABLE \`profiles\` DROP FOREIGN KEY \`FK_315ecd98bd1a42dcf2ec4e2e985\``);
        await queryRunner.query(`ALTER TABLE \`promo_alerts\` DROP FOREIGN KEY \`FK_786941dea2952d17e21626355d7\``);
        await queryRunner.query(`ALTER TABLE \`promo_alerts\` DROP FOREIGN KEY \`FK_aab91d6f90e1b7c80cf2552780f\``);
        await queryRunner.query(`ALTER TABLE \`property_availability\` DROP FOREIGN KEY \`FK_72a85a891e574c9a08f6f62edc8\``);
        await queryRunner.query(`ALTER TABLE \`property_group_memberships\` DROP FOREIGN KEY \`FK_abd19027800f0198931c5295407\``);
        await queryRunner.query(`ALTER TABLE \`property_group_memberships\` DROP FOREIGN KEY \`FK_1e49e229423390107900cad0054\``);
        await queryRunner.query(`ALTER TABLE \`property_images\` DROP FOREIGN KEY \`FK_7a07b6b7f9418bf1d5160106694\``);
        await queryRunner.query(`ALTER TABLE \`property_promos\` DROP FOREIGN KEY \`FK_870506fd9695699a078dfda11e7\``);
        await queryRunner.query(`ALTER TABLE \`saved_search_alerts\` DROP FOREIGN KEY \`FK_83eb2719b230c0aca5d2020e589\``);
        await queryRunner.query(`ALTER TABLE \`verification_documents\` DROP FOREIGN KEY \`FK_83c2693bf96ad158cfb00db3a6d\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_c357057587a1c2afae453515bf6\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_443cc60218090a17d96ea64b058\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_2c75ccf95bf502363885d076e76\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP FOREIGN KEY \`FK_28306518087b40a95df05a43624\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP FOREIGN KEY \`FK_cf064476d403971270369232d80\``);
        await queryRunner.query(`ALTER TABLE \`tourism_services\` DROP FOREIGN KEY \`FK_233b8e5e7662241350d529a48fa\``);
        await queryRunner.query(`ALTER TABLE \`notification_settings\` DROP FOREIGN KEY \`FK_5a8ffc3b89343043c9440d631e2\``);
        await queryRunner.query(`ALTER TABLE \`user_preferences\` DROP FOREIGN KEY \`FK_b6202d1cacc63a0b9c8dac2abd4\``);
        await queryRunner.query(`ALTER TABLE \`support_messages\` DROP FOREIGN KEY \`FK_a6d023327205aee297257d4f0fe\``);
        await queryRunner.query(`ALTER TABLE \`support_messages\` DROP FOREIGN KEY \`FK_af47c9fa96ed606ccf48e195521\``);
        await queryRunner.query(`ALTER TABLE \`support_threads\` DROP FOREIGN KEY \`FK_4b5a435c5e0e30bccf46b83e3ba\``);
        await queryRunner.query(`ALTER TABLE \`support_threads\` DROP FOREIGN KEY \`FK_8475449853d7fae8e59d66f9de7\``);
        await queryRunner.query(`ALTER TABLE \`invitations\` DROP FOREIGN KEY \`FK_b6c9f56adddc26272a8d8643f59\``);
        await queryRunner.query(`ALTER TABLE \`manager_permissions\` DROP FOREIGN KEY \`FK_47e0d2c52f1f2f2759d98be78fd\``);
        await queryRunner.query(`ALTER TABLE \`manager_assignments\` DROP FOREIGN KEY \`FK_5d989ea14604459b64788db8c63\``);
        await queryRunner.query(`ALTER TABLE \`manager_assignments\` DROP FOREIGN KEY \`FK_e9ceb07f2116e7d89fdc718a586\``);
        await queryRunner.query(`ALTER TABLE \`manager_assignments\` DROP FOREIGN KEY \`FK_a481b85a26542b303daf1299603\``);
        await queryRunner.query(`ALTER TABLE \`manager_assignments\` DROP FOREIGN KEY \`FK_89bf0c2c003b0888088b2fbeaa7\``);
        await queryRunner.query(`ALTER TABLE \`property_groups\` DROP FOREIGN KEY \`FK_b6d936acb749bb33c957bb64a9e\``);
        await queryRunner.query(`ALTER TABLE \`properties\` DROP FOREIGN KEY \`FK_97ae9ee8402b8d8d167fa7352ce\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_472b25323af01488f1f66a06b67\``);
        await queryRunner.query(`DROP INDEX \`IDX_comments_userId\` ON \`comments\``);
        await queryRunner.query(`DROP TABLE \`comments\``);
        await queryRunner.query(`DROP INDEX \`IDX_f9c880e929c6fa3bdb17c3f6d1\` ON \`favorites\``);
        await queryRunner.query(`DROP INDEX \`IDX_favorites_propertyId\` ON \`favorites\``);
        await queryRunner.query(`DROP INDEX \`IDX_favorites_userId\` ON \`favorites\``);
        await queryRunner.query(`DROP TABLE \`favorites\``);
        await queryRunner.query(`DROP INDEX \`idx_email_message_id\` ON \`email_events\``);
        await queryRunner.query(`DROP INDEX \`idx_email_recipient_email\` ON \`email_events\``);
        await queryRunner.query(`DROP INDEX \`idx_email_event_type\` ON \`email_events\``);
        await queryRunner.query(`DROP INDEX \`idx_email_created_at\` ON \`email_events\``);
        await queryRunner.query(`DROP TABLE \`email_events\``);
        await queryRunner.query(`DROP INDEX \`IDX_20382c8b78ced4c0fe9fed80ed\` ON \`email_tracked_links\``);
        await queryRunner.query(`DROP INDEX \`IDX_20382c8b78ced4c0fe9fed80ed\` ON \`email_tracked_links\``);
        await queryRunner.query(`DROP INDEX \`IDX_a1434de92f26fb6d950dcb0345\` ON \`email_tracked_links\``);
        await queryRunner.query(`DROP TABLE \`email_tracked_links\``);
        await queryRunner.query(`DROP INDEX \`IDX_notifications_userId\` ON \`notifications\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP TABLE \`payment_receipts\``);
        await queryRunner.query(`DROP TABLE \`transfer_accounts\``);
        await queryRunner.query(`DROP INDEX \`REL_315ecd98bd1a42dcf2ec4e2e98\` ON \`profiles\``);
        await queryRunner.query(`DROP INDEX \`IDX_315ecd98bd1a42dcf2ec4e2e98\` ON \`profiles\``);
        await queryRunner.query(`DROP TABLE \`profiles\``);
        await queryRunner.query(`DROP INDEX \`IDX_6317dffa57c5917cb78fb8c4d1\` ON \`promo_alerts\``);
        await queryRunner.query(`DROP TABLE \`promo_alerts\``);
        await queryRunner.query(`DROP INDEX \`IDX_1be3614f0c4a528ceeb5b21b54\` ON \`property_availability\``);
        await queryRunner.query(`DROP TABLE \`property_availability\``);
        await queryRunner.query(`DROP INDEX \`IDX_b977e6070809644106601ae48c\` ON \`property_group_memberships\``);
        await queryRunner.query(`DROP TABLE \`property_group_memberships\``);
        await queryRunner.query(`DROP INDEX \`IDX_property_images_propertyId\` ON \`property_images\``);
        await queryRunner.query(`DROP TABLE \`property_images\``);
        await queryRunner.query(`DROP TABLE \`property_promos\``);
        await queryRunner.query(`DROP TABLE \`saved_search_alerts\``);
        await queryRunner.query(`DROP INDEX \`IDX_verification_docs_propertyId\` ON \`verification_documents\``);
        await queryRunner.query(`DROP TABLE \`verification_documents\``);
        await queryRunner.query(`DROP INDEX \`IDX_rankings_userId\` ON \`rankings\``);
        await queryRunner.query(`DROP TABLE \`rankings\``);
        await queryRunner.query(`DROP INDEX \`IDX_989f04b0d4b2c2513421b05aea\` ON \`reactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_reactions_userId\` ON \`reactions\``);
        await queryRunner.query(`DROP TABLE \`reactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_c357057587a1c2afae453515bf\` ON \`reviews\``);
        await queryRunner.query(`DROP INDEX \`IDX_reviews_guestId\` ON \`reviews\``);
        await queryRunner.query(`DROP INDEX \`IDX_reviews_propertyId\` ON \`reviews\``);
        await queryRunner.query(`DROP TABLE \`reviews\``);
        await queryRunner.query(`DROP INDEX \`IDX_bookings_guestId\` ON \`bookings\``);
        await queryRunner.query(`DROP INDEX \`IDX_bookings_propertyId\` ON \`bookings\``);
        await queryRunner.query(`DROP TABLE \`bookings\``);
        await queryRunner.query(`DROP INDEX \`IDX_services_providerId\` ON \`tourism_services\``);
        await queryRunner.query(`DROP TABLE \`tourism_services\``);
        await queryRunner.query(`DROP INDEX \`REL_5a8ffc3b89343043c9440d631e\` ON \`notification_settings\``);
        await queryRunner.query(`DROP INDEX \`IDX_5a8ffc3b89343043c9440d631e\` ON \`notification_settings\``);
        await queryRunner.query(`DROP TABLE \`notification_settings\``);
        await queryRunner.query(`DROP INDEX \`REL_b6202d1cacc63a0b9c8dac2abd\` ON \`user_preferences\``);
        await queryRunner.query(`DROP INDEX \`IDX_b6202d1cacc63a0b9c8dac2abd\` ON \`user_preferences\``);
        await queryRunner.query(`DROP TABLE \`user_preferences\``);
        await queryRunner.query(`DROP INDEX \`IDX_support_message_thread\` ON \`support_messages\``);
        await queryRunner.query(`DROP TABLE \`support_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_support_thread_initiator\` ON \`support_threads\``);
        await queryRunner.query(`DROP TABLE \`support_threads\``);
        await queryRunner.query(`DROP TABLE \`invitations\``);
        await queryRunner.query(`DROP INDEX \`IDX_50d3d0212e12f49f2bba0faad5\` ON \`manager_permissions\``);
        await queryRunner.query(`DROP TABLE \`manager_permissions\``);
        await queryRunner.query(`DROP TABLE \`manager_assignments\``);
        await queryRunner.query(`DROP TABLE \`property_groups\``);
        await queryRunner.query(`DROP INDEX \`IDX_properties_hostId\` ON \`properties\``);
        await queryRunner.query(`DROP TABLE \`properties\``);
        await queryRunner.query(`DROP INDEX \`IDX_5f9286e6c25594c6b88c108db7\` ON \`user_roles\``);
        await queryRunner.query(`DROP TABLE \`user_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_53a51a9023bb1e952b1f840312\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_501578f69c24fba9ec42553591\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_75b3a5d8f99f184a376a414542\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`users_address\``);
    }

}
