import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1775575973703 implements MigrationInterface {
    name = 'Migrations1775575973703'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_7b5dcfef06b1d7e8a2dcd98473\` ON \`badge_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe1ea9422b1498bc96e2a720cc\` ON \`badge_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_badge_users_badgeId\` ON \`badge_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_badge_users_userId\` ON \`badge_users\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`userId\`, \`badgeId\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP COLUMN \`unlockedAt\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD \`id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`userId\`, \`badgeId\`, \`id\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD \`unlockedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`badgeId\`, \`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`rewards\` CHANGE \`icon\` \`icon\` varchar(10) NOT NULL DEFAULT '🎁'`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`badgeId\`, \`id\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP COLUMN \`badgeId\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD \`badgeId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP COLUMN \`badgeId\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD \`badgeId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`id\`, \`badgeId\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`id\`, \`badgeId\`, \`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_badge_users_badgeId\` ON \`badge_users\` (\`badgeId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_badge_users_userId\` ON \`badge_users\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_fe1ea9422b1498bc96e2a720cc\` ON \`badge_users\` (\`badgeId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_7b5dcfef06b1d7e8a2dcd98473\` ON \`badge_users\` (\`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`manager_permissions\` ADD CONSTRAINT \`FK_29755f162e12988e468383103a5\` FOREIGN KEY (\`managerId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`manager_permissions\` ADD CONSTRAINT \`FK_e0a0242376af727de8f9ead28b5\` FOREIGN KEY (\`assignedById\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`manager_permissions\` ADD CONSTRAINT \`FK_13ca153aa11fb29f7a583307999\` FOREIGN KEY (\`backendPermissionKey\`) REFERENCES \`rbac_backend_permissions\`(\`permission_key\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`manager_permissions\` ADD CONSTRAINT \`FK_c844e5299603695e5ac69e9f256\` FOREIGN KEY (\`frontendPermissionKey\`) REFERENCES \`rbac_frontend_permissions\`(\`permission_key\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`hyper_manager_permissions\` ADD CONSTRAINT \`FK_904b5c65f59dd736c2a9901b160\` FOREIGN KEY (\`hyperManagerId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`hyper_manager_permissions\` ADD CONSTRAINT \`FK_05c05acc6e7e388f4779a92e13b\` FOREIGN KEY (\`assignedById\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`hyper_manager_permissions\` ADD CONSTRAINT \`FK_b109207c453f1b11114319b5b46\` FOREIGN KEY (\`backendPermissionKey\`) REFERENCES \`rbac_backend_permissions\`(\`permission_key\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`hyper_manager_permissions\` ADD CONSTRAINT \`FK_12f06cb1d8a37a8551f6e21f4cc\` FOREIGN KEY (\`frontendPermissionKey\`) REFERENCES \`rbac_frontend_permissions\`(\`permission_key\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_fee_absorptions\` ADD CONSTRAINT \`FK_5ebe33c8eaaeb2110e403a57e50\` FOREIGN KEY (\`targetPropertyGroupId\`) REFERENCES \`property_groups\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_fee_absorptions\` ADD CONSTRAINT \`FK_c5da153682d1918b83630603102\` FOREIGN KEY (\`targetServiceGroupId\`) REFERENCES \`service_groups\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_fee_absorptions\` ADD CONSTRAINT \`FK_057433cbc0ecfd4b9593a1bf2c9\` FOREIGN KEY (\`targetPropertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_fee_absorptions\` ADD CONSTRAINT \`FK_71cd164aba7e2b38fd64af012e1\` FOREIGN KEY (\`targetServiceId\`) REFERENCES \`tourism_services\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`guest_permissions\` ADD CONSTRAINT \`FK_379c1bf9db6ea101560bd6892e4\` FOREIGN KEY (\`guestId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`guest_permissions\` ADD CONSTRAINT \`FK_039e1fc96e706f37f46cac662e6\` FOREIGN KEY (\`assignedById\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`guest_permissions\` ADD CONSTRAINT \`FK_528b069e5443f5c8e5ea4c35200\` FOREIGN KEY (\`backendPermissionKey\`) REFERENCES \`rbac_backend_permissions\`(\`permission_key\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`guest_permissions\` ADD CONSTRAINT \`FK_4c185ffdc6e98527c3b01caeba3\` FOREIGN KEY (\`frontendPermissionKey\`) REFERENCES \`rbac_frontend_permissions\`(\`permission_key\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cancellation_rules\` ADD CONSTRAINT \`FK_23a1f4b8b6a2956484a22a3f50b\` FOREIGN KEY (\`hostUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cancellation_rules\` ADD CONSTRAINT \`FK_59fe36196698d8627cfc12244a3\` FOREIGN KEY (\`targetPropertyGroupId\`) REFERENCES \`property_groups\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cancellation_rules\` ADD CONSTRAINT \`FK_64e2d04897e0cc2a51ff681b958\` FOREIGN KEY (\`targetServiceGroupId\`) REFERENCES \`service_groups\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cancellation_rules\` ADD CONSTRAINT \`FK_510f1add7bd760de777f549f941\` FOREIGN KEY (\`targetPropertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cancellation_rules\` ADD CONSTRAINT \`FK_21cc77953f6a916b80f3963da81\` FOREIGN KEY (\`targetServiceId\`) REFERENCES \`tourism_services\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`service_verification_documents\` ADD CONSTRAINT \`FK_5cb73c8a0e22627411c98903a2e\` FOREIGN KEY (\`uploadedByUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`service_verification_documents\` ADD CONSTRAINT \`FK_dd8f2c0b66fff3dc144a58c32fb\` FOREIGN KEY (\`reviewedBy\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_2c75ccf95bf502363885d076e76\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_c357057587a1c2afae453515bf6\` FOREIGN KEY (\`bookingId\`) REFERENCES \`bookings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_9563540c43639a0669f68e8ebe3\` FOREIGN KEY (\`serviceId\`) REFERENCES \`tourism_services\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_e2150ffcb408da99a38b09a27a6\` FOREIGN KEY (\`serviceBookingId\`) REFERENCES \`service_bookings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_087f019df0fee33889eb038fe53\` FOREIGN KEY (\`bookingId\`) REFERENCES \`bookings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_8770bd9030a3d13c5f79a7d2e81\` FOREIGN KEY (\`parentId\`) REFERENCES \`comments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reactions\` ADD CONSTRAINT \`FK_f3e1d278edeb2c19a2ddad83f8e\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reactions\` ADD CONSTRAINT \`FK_e71b81457fc37b486d72afb112f\` FOREIGN KEY (\`commentId\`) REFERENCES \`comments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rankings\` ADD CONSTRAINT \`FK_430fa616d89023b764c714fbcf5\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`verification_documents\` ADD CONSTRAINT \`FK_89b3b32056d7201aad71c2d732c\` FOREIGN KEY (\`uploadedByUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`verification_documents\` ADD CONSTRAINT \`FK_2b2db5ac206062527f2cab59b0a\` FOREIGN KEY (\`reviewedBy\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_receipts\` ADD CONSTRAINT \`FK_15f4d38dd33a2cfdbe5b4f0341a\` FOREIGN KEY (\`bookingId\`) REFERENCES \`bookings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_receipts\` ADD CONSTRAINT \`FK_76c6d6fd23cff6d413b4305cafe\` FOREIGN KEY (\`serviceBookingId\`) REFERENCES \`service_bookings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD CONSTRAINT \`FK_7b5dcfef06b1d7e8a2dcd984737\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD CONSTRAINT \`FK_fe1ea9422b1498bc96e2a720cca\` FOREIGN KEY (\`badgeId\`) REFERENCES \`badges\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`service_favorites\` ADD CONSTRAINT \`FK_853df8696c26b0177eb59448e87\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`service_favorites\` ADD CONSTRAINT \`FK_4f343be4c6f9156eddb1ae279ed\` FOREIGN KEY (\`serviceId\`) REFERENCES \`tourism_services\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comment_services\` ADD CONSTRAINT \`FK_87629c32dd33c01c5977100ad63\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comment_services\` ADD CONSTRAINT \`FK_76dad12caf6748ab42d0de7f8b5\` FOREIGN KEY (\`serviceBookingId\`) REFERENCES \`service_bookings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comment_services\` ADD CONSTRAINT \`FK_25ee64c5f287899158c7544f76a\` FOREIGN KEY (\`parentId\`) REFERENCES \`comment_services\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`property_group_properties\` ADD CONSTRAINT \`FK_8bec575ec884800f842d7a20f75\` FOREIGN KEY (\`groupId\`) REFERENCES \`property_groups\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`property_group_properties\` ADD CONSTRAINT \`FK_2c2e60b54a79e37ef3f748e995b\` FOREIGN KEY (\`propertyId\`) REFERENCES \`properties\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`service_group_services\` ADD CONSTRAINT \`FK_7db8a5cb1625d1f2fdf263d0d7d\` FOREIGN KEY (\`groupId\`) REFERENCES \`service_groups\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`service_group_services\` ADD CONSTRAINT \`FK_a35d96c1a392d782e51def89abd\` FOREIGN KEY (\`serviceId\`) REFERENCES \`tourism_services\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`service_group_services\` DROP FOREIGN KEY \`FK_a35d96c1a392d782e51def89abd\``);
        await queryRunner.query(`ALTER TABLE \`service_group_services\` DROP FOREIGN KEY \`FK_7db8a5cb1625d1f2fdf263d0d7d\``);
        await queryRunner.query(`ALTER TABLE \`property_group_properties\` DROP FOREIGN KEY \`FK_2c2e60b54a79e37ef3f748e995b\``);
        await queryRunner.query(`ALTER TABLE \`property_group_properties\` DROP FOREIGN KEY \`FK_8bec575ec884800f842d7a20f75\``);
        await queryRunner.query(`ALTER TABLE \`comment_services\` DROP FOREIGN KEY \`FK_25ee64c5f287899158c7544f76a\``);
        await queryRunner.query(`ALTER TABLE \`comment_services\` DROP FOREIGN KEY \`FK_76dad12caf6748ab42d0de7f8b5\``);
        await queryRunner.query(`ALTER TABLE \`comment_services\` DROP FOREIGN KEY \`FK_87629c32dd33c01c5977100ad63\``);
        await queryRunner.query(`ALTER TABLE \`service_favorites\` DROP FOREIGN KEY \`FK_4f343be4c6f9156eddb1ae279ed\``);
        await queryRunner.query(`ALTER TABLE \`service_favorites\` DROP FOREIGN KEY \`FK_853df8696c26b0177eb59448e87\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP FOREIGN KEY \`FK_fe1ea9422b1498bc96e2a720cca\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP FOREIGN KEY \`FK_7b5dcfef06b1d7e8a2dcd984737\``);
        await queryRunner.query(`ALTER TABLE \`payment_receipts\` DROP FOREIGN KEY \`FK_76c6d6fd23cff6d413b4305cafe\``);
        await queryRunner.query(`ALTER TABLE \`payment_receipts\` DROP FOREIGN KEY \`FK_15f4d38dd33a2cfdbe5b4f0341a\``);
        await queryRunner.query(`ALTER TABLE \`verification_documents\` DROP FOREIGN KEY \`FK_2b2db5ac206062527f2cab59b0a\``);
        await queryRunner.query(`ALTER TABLE \`verification_documents\` DROP FOREIGN KEY \`FK_89b3b32056d7201aad71c2d732c\``);
        await queryRunner.query(`ALTER TABLE \`rankings\` DROP FOREIGN KEY \`FK_430fa616d89023b764c714fbcf5\``);
        await queryRunner.query(`ALTER TABLE \`reactions\` DROP FOREIGN KEY \`FK_e71b81457fc37b486d72afb112f\``);
        await queryRunner.query(`ALTER TABLE \`reactions\` DROP FOREIGN KEY \`FK_f3e1d278edeb2c19a2ddad83f8e\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_8770bd9030a3d13c5f79a7d2e81\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_087f019df0fee33889eb038fe53\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_e2150ffcb408da99a38b09a27a6\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_9563540c43639a0669f68e8ebe3\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_c357057587a1c2afae453515bf6\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_2c75ccf95bf502363885d076e76\``);
        await queryRunner.query(`ALTER TABLE \`service_verification_documents\` DROP FOREIGN KEY \`FK_dd8f2c0b66fff3dc144a58c32fb\``);
        await queryRunner.query(`ALTER TABLE \`service_verification_documents\` DROP FOREIGN KEY \`FK_5cb73c8a0e22627411c98903a2e\``);
        await queryRunner.query(`ALTER TABLE \`cancellation_rules\` DROP FOREIGN KEY \`FK_21cc77953f6a916b80f3963da81\``);
        await queryRunner.query(`ALTER TABLE \`cancellation_rules\` DROP FOREIGN KEY \`FK_510f1add7bd760de777f549f941\``);
        await queryRunner.query(`ALTER TABLE \`cancellation_rules\` DROP FOREIGN KEY \`FK_64e2d04897e0cc2a51ff681b958\``);
        await queryRunner.query(`ALTER TABLE \`cancellation_rules\` DROP FOREIGN KEY \`FK_59fe36196698d8627cfc12244a3\``);
        await queryRunner.query(`ALTER TABLE \`cancellation_rules\` DROP FOREIGN KEY \`FK_23a1f4b8b6a2956484a22a3f50b\``);
        await queryRunner.query(`ALTER TABLE \`guest_permissions\` DROP FOREIGN KEY \`FK_4c185ffdc6e98527c3b01caeba3\``);
        await queryRunner.query(`ALTER TABLE \`guest_permissions\` DROP FOREIGN KEY \`FK_528b069e5443f5c8e5ea4c35200\``);
        await queryRunner.query(`ALTER TABLE \`guest_permissions\` DROP FOREIGN KEY \`FK_039e1fc96e706f37f46cac662e6\``);
        await queryRunner.query(`ALTER TABLE \`guest_permissions\` DROP FOREIGN KEY \`FK_379c1bf9db6ea101560bd6892e4\``);
        await queryRunner.query(`ALTER TABLE \`host_fee_absorptions\` DROP FOREIGN KEY \`FK_71cd164aba7e2b38fd64af012e1\``);
        await queryRunner.query(`ALTER TABLE \`host_fee_absorptions\` DROP FOREIGN KEY \`FK_057433cbc0ecfd4b9593a1bf2c9\``);
        await queryRunner.query(`ALTER TABLE \`host_fee_absorptions\` DROP FOREIGN KEY \`FK_c5da153682d1918b83630603102\``);
        await queryRunner.query(`ALTER TABLE \`host_fee_absorptions\` DROP FOREIGN KEY \`FK_5ebe33c8eaaeb2110e403a57e50\``);
        await queryRunner.query(`ALTER TABLE \`hyper_manager_permissions\` DROP FOREIGN KEY \`FK_12f06cb1d8a37a8551f6e21f4cc\``);
        await queryRunner.query(`ALTER TABLE \`hyper_manager_permissions\` DROP FOREIGN KEY \`FK_b109207c453f1b11114319b5b46\``);
        await queryRunner.query(`ALTER TABLE \`hyper_manager_permissions\` DROP FOREIGN KEY \`FK_05c05acc6e7e388f4779a92e13b\``);
        await queryRunner.query(`ALTER TABLE \`hyper_manager_permissions\` DROP FOREIGN KEY \`FK_904b5c65f59dd736c2a9901b160\``);
        await queryRunner.query(`ALTER TABLE \`manager_permissions\` DROP FOREIGN KEY \`FK_c844e5299603695e5ac69e9f256\``);
        await queryRunner.query(`ALTER TABLE \`manager_permissions\` DROP FOREIGN KEY \`FK_13ca153aa11fb29f7a583307999\``);
        await queryRunner.query(`ALTER TABLE \`manager_permissions\` DROP FOREIGN KEY \`FK_e0a0242376af727de8f9ead28b5\``);
        await queryRunner.query(`ALTER TABLE \`manager_permissions\` DROP FOREIGN KEY \`FK_29755f162e12988e468383103a5\``);
        await queryRunner.query(`DROP INDEX \`IDX_7b5dcfef06b1d7e8a2dcd98473\` ON \`badge_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe1ea9422b1498bc96e2a720cc\` ON \`badge_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_badge_users_userId\` ON \`badge_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_badge_users_badgeId\` ON \`badge_users\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`id\`, \`badgeId\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP COLUMN \`badgeId\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD \`badgeId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP COLUMN \`badgeId\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD \`badgeId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`badgeId\`, \`id\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`userId\`, \`badgeId\`, \`id\`)`);
        await queryRunner.query(`ALTER TABLE \`rewards\` CHANGE \`icon\` \`icon\` varchar(10) NOT NULL DEFAULT '?'`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`userId\`, \`badgeId\`, \`id\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP COLUMN \`unlockedAt\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`userId\`, \`badgeId\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD \`unlockedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD \`id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`userId\`, \`id\`, \`badgeId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_badge_users_userId\` ON \`badge_users\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_badge_users_badgeId\` ON \`badge_users\` (\`badgeId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_fe1ea9422b1498bc96e2a720cc\` ON \`badge_users\` (\`badgeId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_7b5dcfef06b1d7e8a2dcd98473\` ON \`badge_users\` (\`userId\`)`);
    }

}
