import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1778281686989 implements MigrationInterface {
    name = 'Migrations1778281686989'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_blames\` DROP FOREIGN KEY \`FK_user_blames_user\``);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` DROP FOREIGN KEY \`FK_host_payouts_booking\``);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` DROP FOREIGN KEY \`FK_host_payouts_host\``);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` DROP FOREIGN KEY \`FK_host_payouts_receipt\``);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` DROP FOREIGN KEY \`FK_host_payouts_released_by\``);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` DROP FOREIGN KEY \`FK_host_payouts_service_booking\``);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` DROP FOREIGN KEY \`FK_disputes_booking\``);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` DROP FOREIGN KEY \`FK_disputes_guest\``);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` DROP FOREIGN KEY \`FK_disputes_resolved_by\``);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` DROP FOREIGN KEY \`FK_disputes_service_booking\``);
        await queryRunner.query(`ALTER TABLE \`host_fee_debts\` DROP FOREIGN KEY \`FK_debts_dispute\``);
        await queryRunner.query(`ALTER TABLE \`host_fee_debts\` DROP FOREIGN KEY \`FK_debts_host\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP FOREIGN KEY \`FK_7b5dcfef06b1d7e8a2dcd984737\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP FOREIGN KEY \`FK_fe1ea9422b1498bc96e2a720cca\``);
        await queryRunner.query(`DROP INDEX \`IDX_svc_docs_replacesDocumentId\` ON \`service_verification_documents\``);
        await queryRunner.query(`DROP INDEX \`IDX_ver_docs_replacesDocumentId\` ON \`verification_documents\``);
        await queryRunner.query(`DROP INDEX \`IDX_host_payouts_bookingId\` ON \`host_payouts\``);
        await queryRunner.query(`DROP INDEX \`IDX_host_payouts_serviceBookingId\` ON \`host_payouts\``);
        await queryRunner.query(`DROP INDEX \`IDX_booking_disputes_bookingId\` ON \`booking_disputes\``);
        await queryRunner.query(`DROP INDEX \`IDX_booking_disputes_guestUserId\` ON \`booking_disputes\``);
        await queryRunner.query(`DROP INDEX \`IDX_booking_disputes_serviceBookingId\` ON \`booking_disputes\``);
        await queryRunner.query(`DROP INDEX \`IDX_host_fee_debts_disputeId\` ON \`host_fee_debts\``);
        await queryRunner.query(`DROP INDEX \`IDX_7b5dcfef06b1d7e8a2dcd98473\` ON \`badge_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe1ea9422b1498bc96e2a720cc\` ON \`badge_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_badge_users_badgeId\` ON \`badge_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_badge_users_userId\` ON \`badge_users\``);
        await queryRunner.query(`ALTER TABLE \`service_verification_documents\` DROP COLUMN \`replacesDocumentId\``);
        await queryRunner.query(`ALTER TABLE \`verification_documents\` DROP COLUMN \`replacesDocumentId\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`userId\`, \`badgeId\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP COLUMN \`unlockedAt\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD \`id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`userId\`, \`badgeId\`, \`id\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD \`unlockedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`badgeId\`, \`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`user_blames\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`rewards\` CHANGE \`icon\` \`icon\` varchar(10) NOT NULL DEFAULT '🎁'`);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` DROP COLUMN \`bookingId\``);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` ADD \`bookingId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` DROP COLUMN \`serviceBookingId\``);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` ADD \`serviceBookingId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` DROP COLUMN \`receiptId\``);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` ADD \`receiptId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` DROP COLUMN \`bookingId\``);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` ADD \`bookingId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` DROP COLUMN \`serviceBookingId\``);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` ADD \`serviceBookingId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`host_fee_debts\` DROP COLUMN \`disputeId\``);
        await queryRunner.query(`ALTER TABLE \`host_fee_debts\` ADD \`disputeId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`badgeId\`, \`id\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP COLUMN \`badgeId\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD \`badgeId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP COLUMN \`badgeId\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD \`badgeId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`id\`, \`badgeId\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`id\`, \`badgeId\`, \`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_f4d7a8df76e97a256587ec29b9\` ON \`host_payouts\` (\`bookingId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_7231049265b7acbbb77f14bba4\` ON \`host_payouts\` (\`serviceBookingId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_9b4b17ad42f8d9d971349da586\` ON \`host_payouts\` (\`hostUserId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_29f8cae938b0e6709bacd957d1\` ON \`booking_disputes\` (\`bookingId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_288ffeb68980774b28f773e70a\` ON \`booking_disputes\` (\`serviceBookingId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_188e35b5af0b02c58f5e4b507a\` ON \`booking_disputes\` (\`guestUserId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_90101968179b5bbf1af88c6afe\` ON \`host_fee_debts\` (\`hostUserId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_badge_users_badgeId\` ON \`badge_users\` (\`badgeId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_badge_users_userId\` ON \`badge_users\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_fe1ea9422b1498bc96e2a720cc\` ON \`badge_users\` (\`badgeId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_7b5dcfef06b1d7e8a2dcd98473\` ON \`badge_users\` (\`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`user_blames\` ADD CONSTRAINT \`FK_62d791b06f49dba14758791c715\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` ADD CONSTRAINT \`FK_f4d7a8df76e97a256587ec29b98\` FOREIGN KEY (\`bookingId\`) REFERENCES \`bookings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` ADD CONSTRAINT \`FK_7231049265b7acbbb77f14bba46\` FOREIGN KEY (\`serviceBookingId\`) REFERENCES \`service_bookings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` ADD CONSTRAINT \`FK_d7c0994b9024a11bce561437b73\` FOREIGN KEY (\`receiptId\`) REFERENCES \`payment_receipts\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` ADD CONSTRAINT \`FK_9b4b17ad42f8d9d971349da5863\` FOREIGN KEY (\`hostUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` ADD CONSTRAINT \`FK_7e7779b1040d6544b8930e0e1a8\` FOREIGN KEY (\`releasedByUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` ADD CONSTRAINT \`FK_29f8cae938b0e6709bacd957d15\` FOREIGN KEY (\`bookingId\`) REFERENCES \`bookings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` ADD CONSTRAINT \`FK_288ffeb68980774b28f773e70a2\` FOREIGN KEY (\`serviceBookingId\`) REFERENCES \`service_bookings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` ADD CONSTRAINT \`FK_188e35b5af0b02c58f5e4b507a2\` FOREIGN KEY (\`guestUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` ADD CONSTRAINT \`FK_676c69c752120bc803bf4d12e6d\` FOREIGN KEY (\`resolvedByUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_fee_debts\` ADD CONSTRAINT \`FK_90101968179b5bbf1af88c6afea\` FOREIGN KEY (\`hostUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_fee_debts\` ADD CONSTRAINT \`FK_549d5121f1ce702bd4179fe10ef\` FOREIGN KEY (\`disputeId\`) REFERENCES \`booking_disputes\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD CONSTRAINT \`FK_7b5dcfef06b1d7e8a2dcd984737\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD CONSTRAINT \`FK_fe1ea9422b1498bc96e2a720cca\` FOREIGN KEY (\`badgeId\`) REFERENCES \`badges\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP FOREIGN KEY \`FK_fe1ea9422b1498bc96e2a720cca\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP FOREIGN KEY \`FK_7b5dcfef06b1d7e8a2dcd984737\``);
        await queryRunner.query(`ALTER TABLE \`host_fee_debts\` DROP FOREIGN KEY \`FK_549d5121f1ce702bd4179fe10ef\``);
        await queryRunner.query(`ALTER TABLE \`host_fee_debts\` DROP FOREIGN KEY \`FK_90101968179b5bbf1af88c6afea\``);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` DROP FOREIGN KEY \`FK_676c69c752120bc803bf4d12e6d\``);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` DROP FOREIGN KEY \`FK_188e35b5af0b02c58f5e4b507a2\``);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` DROP FOREIGN KEY \`FK_288ffeb68980774b28f773e70a2\``);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` DROP FOREIGN KEY \`FK_29f8cae938b0e6709bacd957d15\``);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` DROP FOREIGN KEY \`FK_7e7779b1040d6544b8930e0e1a8\``);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` DROP FOREIGN KEY \`FK_9b4b17ad42f8d9d971349da5863\``);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` DROP FOREIGN KEY \`FK_d7c0994b9024a11bce561437b73\``);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` DROP FOREIGN KEY \`FK_7231049265b7acbbb77f14bba46\``);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` DROP FOREIGN KEY \`FK_f4d7a8df76e97a256587ec29b98\``);
        await queryRunner.query(`ALTER TABLE \`user_blames\` DROP FOREIGN KEY \`FK_62d791b06f49dba14758791c715\``);
        await queryRunner.query(`DROP INDEX \`IDX_7b5dcfef06b1d7e8a2dcd98473\` ON \`badge_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe1ea9422b1498bc96e2a720cc\` ON \`badge_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_badge_users_userId\` ON \`badge_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_badge_users_badgeId\` ON \`badge_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_90101968179b5bbf1af88c6afe\` ON \`host_fee_debts\``);
        await queryRunner.query(`DROP INDEX \`IDX_188e35b5af0b02c58f5e4b507a\` ON \`booking_disputes\``);
        await queryRunner.query(`DROP INDEX \`IDX_288ffeb68980774b28f773e70a\` ON \`booking_disputes\``);
        await queryRunner.query(`DROP INDEX \`IDX_29f8cae938b0e6709bacd957d1\` ON \`booking_disputes\``);
        await queryRunner.query(`DROP INDEX \`IDX_9b4b17ad42f8d9d971349da586\` ON \`host_payouts\``);
        await queryRunner.query(`DROP INDEX \`IDX_7231049265b7acbbb77f14bba4\` ON \`host_payouts\``);
        await queryRunner.query(`DROP INDEX \`IDX_f4d7a8df76e97a256587ec29b9\` ON \`host_payouts\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`id\`, \`badgeId\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP COLUMN \`badgeId\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD \`badgeId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP COLUMN \`badgeId\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD \`badgeId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`badgeId\`, \`id\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`userId\`, \`badgeId\`, \`id\`)`);
        await queryRunner.query(`ALTER TABLE \`host_fee_debts\` DROP COLUMN \`disputeId\``);
        await queryRunner.query(`ALTER TABLE \`host_fee_debts\` ADD \`disputeId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` DROP COLUMN \`serviceBookingId\``);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` ADD \`serviceBookingId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` DROP COLUMN \`bookingId\``);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` ADD \`bookingId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` DROP COLUMN \`receiptId\``);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` ADD \`receiptId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` DROP COLUMN \`serviceBookingId\``);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` ADD \`serviceBookingId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` DROP COLUMN \`bookingId\``);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` ADD \`bookingId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`rewards\` CHANGE \`icon\` \`icon\` varchar(10) NOT NULL DEFAULT '?'`);
        await queryRunner.query(`ALTER TABLE \`user_blames\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`userId\`, \`badgeId\`, \`id\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP COLUMN \`unlockedAt\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`userId\`, \`badgeId\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD \`unlockedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD \`id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD PRIMARY KEY (\`userId\`, \`id\`, \`badgeId\`)`);
        await queryRunner.query(`ALTER TABLE \`verification_documents\` ADD \`replacesDocumentId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`service_verification_documents\` ADD \`replacesDocumentId\` varchar(36) NULL`);
        await queryRunner.query(`CREATE INDEX \`IDX_badge_users_userId\` ON \`badge_users\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_badge_users_badgeId\` ON \`badge_users\` (\`badgeId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_fe1ea9422b1498bc96e2a720cc\` ON \`badge_users\` (\`badgeId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_7b5dcfef06b1d7e8a2dcd98473\` ON \`badge_users\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_host_fee_debts_disputeId\` ON \`host_fee_debts\` (\`disputeId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_booking_disputes_serviceBookingId\` ON \`booking_disputes\` (\`serviceBookingId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_booking_disputes_guestUserId\` ON \`booking_disputes\` (\`guestUserId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_booking_disputes_bookingId\` ON \`booking_disputes\` (\`bookingId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_host_payouts_serviceBookingId\` ON \`host_payouts\` (\`serviceBookingId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_host_payouts_bookingId\` ON \`host_payouts\` (\`bookingId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ver_docs_replacesDocumentId\` ON \`verification_documents\` (\`replacesDocumentId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_svc_docs_replacesDocumentId\` ON \`service_verification_documents\` (\`replacesDocumentId\`)`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD CONSTRAINT \`FK_fe1ea9422b1498bc96e2a720cca\` FOREIGN KEY (\`badgeId\`) REFERENCES \`badges\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`badge_users\` ADD CONSTRAINT \`FK_7b5dcfef06b1d7e8a2dcd984737\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_fee_debts\` ADD CONSTRAINT \`FK_debts_host\` FOREIGN KEY (\`hostUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_fee_debts\` ADD CONSTRAINT \`FK_debts_dispute\` FOREIGN KEY (\`disputeId\`) REFERENCES \`booking_disputes\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` ADD CONSTRAINT \`FK_disputes_service_booking\` FOREIGN KEY (\`serviceBookingId\`) REFERENCES \`service_bookings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` ADD CONSTRAINT \`FK_disputes_resolved_by\` FOREIGN KEY (\`resolvedByUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` ADD CONSTRAINT \`FK_disputes_guest\` FOREIGN KEY (\`guestUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`booking_disputes\` ADD CONSTRAINT \`FK_disputes_booking\` FOREIGN KEY (\`bookingId\`) REFERENCES \`bookings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` ADD CONSTRAINT \`FK_host_payouts_service_booking\` FOREIGN KEY (\`serviceBookingId\`) REFERENCES \`service_bookings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` ADD CONSTRAINT \`FK_host_payouts_released_by\` FOREIGN KEY (\`releasedByUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` ADD CONSTRAINT \`FK_host_payouts_receipt\` FOREIGN KEY (\`receiptId\`) REFERENCES \`payment_receipts\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` ADD CONSTRAINT \`FK_host_payouts_host\` FOREIGN KEY (\`hostUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_payouts\` ADD CONSTRAINT \`FK_host_payouts_booking\` FOREIGN KEY (\`bookingId\`) REFERENCES \`bookings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_blames\` ADD CONSTRAINT \`FK_user_blames_user\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
