export const SERVICE_CATEGORIES = [
  'restaurant',
  'walking_tour',
  'cycling_tour',
  'car_tour',
  'bus_tour',
  'horse_tour',
  'boat_tour',
  'beauty_salon',
  'massage',
  'hammam',
  'tourist_guide',
  'photography',
  'park_visit',
  'beach_visit',
  'nature_excursion',
  'regional_event',
  'cooking_class',
  'art_class',
  'drawing_class',
  'sport_activity',
  'spa',
  'shopping_tour',
  'cultural_visit',
  'nightlife',
  // Artisan & crafts
  'silver_jewelry',
  'gold_jewelry',
  'traditional_jewelry',
  'pottery',
  'leather_craft',
  'carpet_weaving',
  'woodwork',
  'calligraphy',
  'henna_art',
  'other',
] as const;

export const CATEGORY_ICONS: Record<string, string> = {
  restaurant: '🍽️',
  walking_tour: '🚶',
  cycling_tour: '🚴',
  car_tour: '🚗',
  bus_tour: '🚌',
  horse_tour: '🐴',
  boat_tour: '⛵',
  beauty_salon: '💇',
  massage: '💆',
  hammam: '🛁',
  tourist_guide: '🗺️',
  photography: '📸',
  park_visit: '🌳',
  beach_visit: '🏖️',
  nature_excursion: '🏔️',
  regional_event: '🎪',
  cooking_class: '👨‍🍳',
  art_class: '🎨',
  drawing_class: '✏️',
  sport_activity: '⚽',
  spa: '🧖',
  shopping_tour: '🛍️',
  cultural_visit: '🏛️',
  nightlife: '🌙',
  // Artisan & crafts
  silver_jewelry: '🪙',
  gold_jewelry: '💍',
  traditional_jewelry: '📿',
  pottery: '🏺',
  leather_craft: '👜',
  carpet_weaving: '🧶',
  woodwork: '🪵',
  calligraphy: '🖋️',
  henna_art: '🤲',
  other: '✨',
};

/** Required documents for service provider verification */
export const SERVICE_REQUIRED_DOCUMENTS = [
  'national_id',
  'registre_commerce',
  'avis_imposition',
  'certificat_tourisme',
  'certificat_culture',
  'certificat_artisanat',
  'licence_activite',
] as const;

export const SERVICE_DOCUMENT_LABELS: Record<string, { fr: string; en: string }> = {
  national_id: { fr: 'Carte d\'identité nationale', en: 'National ID Card' },
  registre_commerce: { fr: 'Registre de commerce', en: 'Commercial Register' },
  avis_imposition: { fr: 'Avis d\'imposition', en: 'Tax Notice' },
  certificat_tourisme: { fr: 'Certificat du Ministère du Tourisme', en: 'Ministry of Tourism Certificate' },
  certificat_culture: { fr: 'Certificat du Ministère de la Culture', en: 'Ministry of Culture Certificate' },
  certificat_artisanat: { fr: 'Certificat du Ministère de l\'Artisanat', en: 'Ministry of Craftsmanship Certificate' },
  licence_activite: { fr: 'Licence d\'activité', en: 'Activity License' },
};
