import type { TourismService } from '@/types/tourism-service.types';

export const MOCK_SERVICES: TourismService[] = [
  {
    id: 'svc-1',
    providerId: 1,
    title: { fr: 'Balade en Casbah d\'Alger', en: 'Algiers Casbah Walking Tour', ar: 'جولة سيرًا في قصبة الجزائر' },
    description: { fr: 'Découvrez les ruelles historiques de la Casbah', en: 'Discover the historic alleys of the Casbah', ar: 'اكتشف الأزقة التاريخية للقصبة' },
    category: 'walking_tour',
    status: 'published',
    price: 3500,
    currency: 'DZD',
    pricingType: 'per_person',
    duration: 3,
    durationUnit: 'hours',
    minParticipants: 2,
    maxParticipants: 15,
    latitude: 36.7853,
    longitude: 3.0588,
    address: 'Casbah, Alger',
    city: 'Alger',
    wilaya: 'Alger',
    country: 'Algeria',
    images: ['https://images.unsplash.com/photo-1583425423320-0f5e5af4aae0?w=800'],
    includes: { fr: ['Guide local', 'Thé à la menthe'], en: ['Local guide', 'Mint tea'], ar: ['مرشد محلي', 'شاي بالنعناع'] },
    requirements: { fr: ['Chaussures confortables'], en: ['Comfortable shoes'], ar: ['أحذية مريحة'] },
    languages: ['fr', 'en', 'ar'],
    tags: ['culture', 'history', 'walking'],
    averageRating: 4.8,
    reviewCount: 42,
    bookingCount: 156,
    isAvailable: true,
    isVerified: true,
    instantBooking: true,
    minAge: 0,
    cancellationPolicy: 'flexible',
    createdAt: '2024-01-15',
    updatedAt: '2024-03-20',
  },
  {
    id: 'svc-2',
    providerId: 2,
    title: { fr: 'Cours de cuisine traditionnelle', en: 'Traditional Cooking Class', ar: 'دروس طبخ تقليدي' },
    description: { fr: 'Apprenez les secrets du couscous et des tajines', en: 'Learn the secrets of couscous and tajines', ar: 'تعلم أسرار الكسكس والطاجين' },
    category: 'cooking_class',
    status: 'published',
    price: 5000,
    currency: 'DZD',
    pricingType: 'per_person',
    duration: 4,
    durationUnit: 'hours',
    minParticipants: 2,
    maxParticipants: 8,
    latitude: 36.7538,
    longitude: 3.0588,
    city: 'Alger',
    wilaya: 'Alger',
    country: 'Algeria',
    images: ['https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800'],
    includes: { fr: ['Ingrédients', 'Repas complet', 'Recettes'], en: ['Ingredients', 'Full meal', 'Recipes'], ar: ['المكونات', 'وجبة كاملة', 'وصفات'] },
    languages: ['fr', 'ar'],
    tags: ['food', 'cooking', 'culture'],
    averageRating: 4.9,
    reviewCount: 67,
    bookingCount: 230,
    isAvailable: true,
    isVerified: true,
    instantBooking: false,
    minAge: 12,
    cancellationPolicy: 'moderate',
    createdAt: '2024-02-01',
    updatedAt: '2024-03-25',
  },
  {
    id: 'svc-3',
    providerId: 3,
    title: { fr: 'Hammam & Spa traditionnel', en: 'Traditional Hammam & Spa', ar: 'حمام وسبا تقليدي' },
    description: { fr: 'Relaxation dans un hammam authentique', en: 'Relaxation in an authentic hammam', ar: 'استرخاء في حمام تقليدي أصيل' },
    category: 'hammam',
    status: 'published',
    price: 4000,
    currency: 'DZD',
    pricingType: 'per_person',
    duration: 2,
    durationUnit: 'hours',
    minParticipants: 1,
    maxParticipants: 6,
    latitude: 36.7650,
    longitude: 3.0500,
    city: 'Alger',
    wilaya: 'Alger',
    country: 'Algeria',
    images: ['https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800'],
    includes: { fr: ['Savon noir', 'Gant Kessa', 'Thé'], en: ['Black soap', 'Kessa glove', 'Tea'], ar: ['صابون أسود', 'قفاز كيسة', 'شاي'] },
    languages: ['fr', 'ar'],
    tags: ['wellness', 'spa', 'hammam'],
    averageRating: 4.7,
    reviewCount: 89,
    bookingCount: 340,
    isAvailable: true,
    isVerified: true,
    instantBooking: true,
    minAge: 16,
    cancellationPolicy: 'strict',
    createdAt: '2024-01-20',
    updatedAt: '2024-03-18',
  },
  {
    id: 'svc-4',
    providerId: 4,
    title: { fr: 'Safari à cheval dans le Sahara', en: 'Sahara Horse Safari', ar: 'سفاري بالخيول في الصحراء' },
    description: { fr: 'Traversez les dunes du Sahara à cheval', en: 'Cross the Sahara dunes on horseback', ar: 'اعبر كثبان الصحراء على ظهر الحصان' },
    category: 'horse_tour',
    status: 'published',
    price: 12000,
    currency: 'DZD',
    pricingType: 'per_person',
    duration: 1,
    durationUnit: 'days',
    minParticipants: 2,
    maxParticipants: 10,
    latitude: 32.4911,
    longitude: 3.6694,
    city: 'Ghardaia',
    wilaya: 'Ghardaia',
    country: 'Algeria',
    images: ['https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800'],
    includes: { fr: ['Cheval', 'Guide', 'Déjeuner', 'Eau'], en: ['Horse', 'Guide', 'Lunch', 'Water'], ar: ['حصان', 'مرشد', 'غداء', 'ماء'] },
    requirements: { fr: ['Expérience équitation recommandée'], en: ['Riding experience recommended'], ar: ['يُوصى بخبرة في ركوب الخيل'] },
    languages: ['fr', 'ar', 'en'],
    tags: ['adventure', 'sahara', 'horse'],
    averageRating: 4.6,
    reviewCount: 23,
    bookingCount: 78,
    isAvailable: true,
    isVerified: true,
    instantBooking: false,
    minAge: 14,
    cancellationPolicy: 'moderate',
    createdAt: '2024-02-10',
    updatedAt: '2024-03-22',
  },
  {
    id: 'svc-5',
    providerId: 5,
    title: { fr: 'Photographe professionnel', en: 'Professional Photographer', ar: 'مصور محترف' },
    description: { fr: 'Séance photo dans les plus beaux sites', en: 'Photo session at the most beautiful sites', ar: 'جلسة تصوير في أجمل المواقع' },
    category: 'photography',
    status: 'published',
    price: 8000,
    currency: 'DZD',
    pricingType: 'per_hour',
    duration: 2,
    durationUnit: 'hours',
    minParticipants: 1,
    maxParticipants: 10,
    latitude: 36.7538,
    longitude: 3.0588,
    city: 'Alger',
    wilaya: 'Alger',
    country: 'Algeria',
    images: ['https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800'],
    includes: { fr: ['50 photos retouchées', 'Galerie en ligne'], en: ['50 retouched photos', 'Online gallery'], ar: ['50 صورة معدلة', 'معرض أونلاين'] },
    languages: ['fr', 'en'],
    tags: ['photography', 'portrait', 'memories'],
    averageRating: 4.9,
    reviewCount: 55,
    bookingCount: 190,
    isAvailable: true,
    isVerified: true,
    instantBooking: true,
    minAge: 0,
    cancellationPolicy: 'flexible',
    createdAt: '2024-01-25',
    updatedAt: '2024-03-19',
  },
  {
    id: 'svc-6',
    providerId: 6,
    title: { fr: 'Excursion plage de Tipaza', en: 'Tipaza Beach Excursion', ar: 'رحلة شاطئ تيبازة' },
    description: { fr: 'Journée plage avec visite des ruines romaines', en: 'Beach day with Roman ruins visit', ar: 'يوم على الشاطئ مع زيارة الآثار الرومانية' },
    category: 'beach_visit',
    status: 'published',
    price: 6000,
    currency: 'DZD',
    pricingType: 'per_person',
    duration: 1,
    durationUnit: 'days',
    minParticipants: 4,
    maxParticipants: 20,
    latitude: 36.5942,
    longitude: 2.4477,
    city: 'Tipaza',
    wilaya: 'Tipaza',
    country: 'Algeria',
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
    includes: { fr: ['Transport', 'Entrée ruines', 'Déjeuner'], en: ['Transport', 'Ruins entry', 'Lunch'], ar: ['نقل', 'دخول الآثار', 'غداء'] },
    languages: ['fr', 'ar'],
    tags: ['beach', 'history', 'nature'],
    averageRating: 4.5,
    reviewCount: 34,
    bookingCount: 120,
    isAvailable: true,
    isVerified: false,
    instantBooking: false,
    minAge: 0,
    cancellationPolicy: 'moderate',
    createdAt: '2024-02-15',
    updatedAt: '2024-03-21',
  },
  {
    id: 'svc-7',
    providerId: 1,
    title: { fr: 'Bijouterie Traditionnelle en Argent', en: 'Traditional Silver Jewelry Workshop', ar: 'ورشة مجوهرات فضية تقليدية' },
    description: { fr: 'Art ancestral de la bijouterie berbère en argent', en: 'Ancestral art of Berber silver jewelry', ar: 'فن صناعة المجوهرات الفضية البربرية' },
    category: 'silver_jewelry',
    status: 'published',
    price: 7000,
    currency: 'DZD',
    pricingType: 'per_person',
    duration: 4,
    durationUnit: 'hours',
    minParticipants: 1,
    maxParticipants: 6,
    latitude: 32.4911,
    longitude: 3.6694,
    city: 'Ghardaia',
    wilaya: 'Ghardaia',
    country: 'Algeria',
    images: ['https://images.unsplash.com/photo-1515562141589-67f0d7f68681?w=800'],
    includes: { fr: ['Matériaux', 'Outils', 'Bijou à emporter'], en: ['Materials', 'Tools', 'Jewelry to take home'] },
    languages: ['fr', 'ar'],
    tags: ['artisan', 'silver', 'jewelry', 'berber'],
    averageRating: 4.9,
    reviewCount: 38,
    bookingCount: 95,
    isAvailable: true,
    isVerified: true,
    instantBooking: false,
    minAge: 12,
    cancellationPolicy: 'moderate',
    createdAt: '2024-03-01',
    updatedAt: '2024-03-25',
  },
  {
    id: 'svc-8',
    providerId: 2,
    title: { fr: 'Poterie Traditionnelle de Kabylie', en: 'Traditional Kabyle Pottery', ar: 'فخار تقليدي قبائلي' },
    description: { fr: 'Poterie kabyle avec motifs géométriques ancestraux', en: 'Kabyle pottery with ancestral geometric patterns', ar: 'فخار قبائلي بأنماط هندسية عريقة' },
    category: 'pottery',
    status: 'published',
    price: 4500,
    currency: 'DZD',
    pricingType: 'per_person',
    duration: 3,
    durationUnit: 'hours',
    minParticipants: 2,
    maxParticipants: 10,
    latitude: 36.7169,
    longitude: 4.0497,
    city: 'Tizi Ouzou',
    wilaya: 'Tizi Ouzou',
    country: 'Algeria',
    images: ['https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800'],
    includes: { fr: ['Argile', 'Outils', 'Pièce à emporter'], en: ['Clay', 'Tools', 'Piece to take home'] },
    languages: ['fr', 'ar'],
    tags: ['artisan', 'pottery', 'kabyle'],
    averageRating: 4.7,
    reviewCount: 41,
    bookingCount: 110,
    isAvailable: true,
    isVerified: true,
    instantBooking: false,
    minAge: 0,
    cancellationPolicy: 'flexible',
    createdAt: '2024-02-20',
    updatedAt: '2024-03-24',
  },
  {
    id: 'svc-9',
    providerId: 3,
    title: { fr: 'Art du Henné - Atelier', en: 'Henna Art Workshop', ar: 'ورشة فن الحناء' },
    description: { fr: 'Motifs traditionnels algériens de henné', en: 'Traditional Algerian henna patterns', ar: 'أنماط الحناء الجزائرية التقليدية' },
    category: 'henna_art',
    status: 'published',
    price: 3000,
    currency: 'DZD',
    pricingType: 'per_person',
    duration: 2,
    durationUnit: 'hours',
    minParticipants: 2,
    maxParticipants: 8,
    latitude: 36.7538,
    longitude: 3.0588,
    city: 'Alger',
    wilaya: 'Alger',
    country: 'Algeria',
    images: ['https://images.unsplash.com/photo-1570554886111-e80fcca6a029?w=800'],
    includes: { fr: ['Henné naturel', 'Modèles'], en: ['Natural henna', 'Patterns'] },
    languages: ['fr', 'ar', 'en'],
    tags: ['artisan', 'henna', 'beauty', 'traditional'],
    averageRating: 4.8,
    reviewCount: 56,
    bookingCount: 180,
    isAvailable: true,
    isVerified: true,
    instantBooking: true,
    minAge: 0,
    cancellationPolicy: 'flexible',
    createdAt: '2024-01-30',
    updatedAt: '2024-03-22',
  },
];
