export const DETAIL_NAME_NULL = { className: 'name', content: '-' };
export const DETAIL_NAME_VALUE = { className: 'name', content: 'name' };
export const transformPricingDifference = [{ name: 'Premium' }, { price: 1000 }, { cta: 5 }];

export const pricingObjectMock: any = {
  additionalOptions: {},
  id: '1',
  name: 'Premium',
  price: 1000,
  currency: 1,
  nrOfAdmins: 50,
  cube: false,
  kpi: true,
  escrow: true,
  automaticAdditionOfRules: true,
  automaticBilling: true,
  unusedBudgetRefund: true,
  maxEmailPerMonth: true,
  dataExport: true,
  archives: true,
  maxUsers: 100,
  dataStorageCapacity: 100,
  cta: 5,
  setup: 1,
  typeOfPrograms: 2,
  frequenciesOfPayment: null,
  nrOfStorytellings: 2,
  marketingAutomation: false,
  hierarchicLevels: false,
  nrOfMarketplacePartners: 2,
  prepackagedMarketplaces: false
};

export const processedPricingMock = [
  { setup: 1 },
  { typeOfPrograms: 2 },
  { nrOfAdmins: 50 },
  { cube: false },
  { kpi: true },
  { escrow: true },
  { automaticAdditionOfRules: true },
  { automaticBilling: true },
  { unusedBudgetRefund: true },
  { dataExport: true },
  { maxEmailPerMonth: true },
  { maxUsers: 100 },
  { dataStorageCapacity: 100 },
  { archives: true },
  { frequenciesOfPayment: null }
];

export const transformPricingBaseMock = [
  { className: 'name', content: 'best seller' },
  { className: 'setup', content: 1 },
  { className: 'typeOfPrograms', content: 2 },
  { className: 'nrOfAdmins', content: 50 },
  { className: 'cube', content: false },
  { className: 'kpi', content: true },
  { className: 'escrow', content: true },
  { className: 'automaticBilling', content: true },
  { className: 'unusedBudgetRefund', content: true },
  { className: 'dataExport', content: true },
  { className: 'maxUsers', content: 100 },
  { className: 'dataStorageCapacity', content: 100 }
];

export const RESPONSE_MOCK = [
  {
    id: '1',
    name: 'Freemium',
    price: 1000,
    currency: 1,
    nrOfAdmins: 1,
    nrOfStorytellings: 10,
    marketingAutomation: false,
    cube: false,
    hierarchicLevels: false,
    kpi: true,
    escrow: true,
    automaticBilling: null,
    nrOfMarketplacePartners: 12,
    prepackagedMarket: true,
    unusedBudgetRefund: true,
    dataExport: true,
    maxUsers: 100,
    dataStorageCapacity: 100,
    cta: 5,
    setup: 1,
    typeOfPrograms: 2,
    frequenciesOfPayment: null
  },
  {
    id: '1',
    name: 'Access',
    price: 1000,
    currency: 1,
    nrOfAdmins: 3,
    nrOfStorytellings: 10,
    marketingAutomation: false,
    cube: false,
    hierarchicLevels: false,
    kpi: true,
    escrow: true,
    automaticBilling: true,
    nrOfMarketplacePartners: 12,
    prepackagedMarket: true,
    unusedBudgetRefund: true,
    dataExport: true,
    maxUsers: 100,
    dataStorageCapacity: 100,
    cta: 5,
    setup: 1,
    typeOfPrograms: 2,
    frequenciesOfPayment: null
  },
  {
    id: '1',
    name: 'Best seller',
    price: 1000,
    currency: 1,
    nrOfAdmins: 5,
    nrOfStorytellings: 10,
    marketingAutomation: false,
    cube: false,
    hierarchicLevels: false,
    kpi: true,
    escrow: true,
    automaticBilling: true,
    nrOfMarketplacePartners: 12,
    prepackagedMarket: true,
    unusedBudgetRefund: true,
    dataExport: true,
    maxUsers: 100,
    dataStorageCapacity: 100,
    cta: 5,
    setup: 1,
    typeOfPrograms: 2,
    frequenciesOfPayment: null
  },
  {
    id: '1',
    name: 'Premium',
    price: 1000,
    currency: 1,
    nrOfAdmins: 50,
    nrOfStorytellings: 10,
    marketingAutomation: false,
    cube: false,
    hierarchicLevels: false,
    kpi: true,
    escrow: true,
    automaticBilling: true,
    nrOfMarketplacePartners: 12,
    prepackagedMarket: true,
    unusedBudgetRefund: true,
    dataExport: true,
    maxUsers: 100,
    dataStorageCapacity: 100,
    cta: 5,
    setup: 1,
    typeOfPrograms: 2,
    frequenciesOfPayment: null
  }
];

export const FREQUENCY_PLAN_MOCK = {
  currency: 1,
  discount: 5,
  frequencyType: 3,
  id: 15,
  paymentValue: 4809,
  pricePerMonth: 1603
};

export const FREQUENCY_PRICING_PLAN = [
  { className: 'name', content: 'access' },
  { className: 'price', content: 50 },
  { className: 'cta', content: 2 },
  { className: 'setup', content: 2 },
  { className: 'typeOfPrograms', content: 1 },
  { className: 'nrOfAdmins', content: 1 },
  { className: 'nrOfStorytellings', content: 1 },
  { className: 'marketingAutomation', content: 'CHECKED' },
  { className: 'cube', content: 'CHECKED' },
  { className: 'hierarchicLevels', content: 'CHECKED' },
  { className: 'kpi', content: 'CHECKED' },
  { className: 'escrow', content: 'CHECKED' },
  { className: 'automaticAdditionOfRules', content: 'UNCHECKED' },
  { className: 'automaticBilling', content: 'CHECKED' },
  { className: 'nrOfMarketplacePartners', content: 5 },
  { className: 'prepackagedMarketplaces', content: 'UNCHECKED' },
  { className: 'unusedBudgetRefund', content: 'UNCHECKED' },
  { className: 'dataExport', content: 'CHECKED' },
  { className: 'maxEmailPerMonth', content: 400 },
  { className: 'maxUsers', content: 100 },
  { className: 'dataStorageCapacity', content: 50 },
  { className: 'archives', content: 6 },
  {
    className: 'frequenciesOfPayment',
    content: [
      { id: 5, frequencyType: 1, pricePerMonth: 350, paymentValue: 4200, discount: 20 },
      { id: 6, frequencyType: 2, pricePerMonth: 393, paymentValue: 2362, discount: 10 },
      { id: 7, frequencyType: 3, pricePerMonth: 415, paymentValue: 1246, discount: 5 },
      { id: 8, frequencyType: 4, pricePerMonth: 437, paymentValue: 437, discount: 0 }
    ]
  },
  { className: 'cta', content: 2 }
];
